#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
lake --wfail build

# Report and check only the public proof entry points.
axioms=$(lake env lean /dev/stdin <<'LEAN'
import ECDSAAdd
#print axioms ECDSAAdd.andComputeErase_spec
#print axioms ECDSAAdd.andComputeErase_correct
#print axioms ECDSAAdd.andComputeErase_toffoliCount
#print axioms ECDSAAdd.andComputeErase_measurementCount
#print axioms ECDSAAdd.andComputeErase_qubitCount
#print axioms ECDSAAdd.Triple.seq
#print axioms ECDSAAdd.Triple.conseq
#print axioms ECDSAAdd.Triple.frame
#print axioms ECDSAAdd.Arithmetic.fullAdder_spec
#print axioms ECDSAAdd.Arithmetic.eraseCarry_spec
#print axioms ECDSAAdd.Arithmetic.notRegister_spec
#print axioms ECDSAAdd.Arithmetic.add_spec
#print axioms ECDSAAdd.Arithmetic.sub_spec
#print axioms ECDSAAdd.Arithmetic.add_erase_spec
#print axioms ECDSAAdd.Arithmetic.sub_erase_spec
#print axioms ECDSAAdd.Arithmetic.add_twice_spec
#print axioms ECDSAAdd.Arithmetic.add_resources
#print axioms ECDSAAdd.Arithmetic.sub_resources
#print axioms ECDSAAdd.Arithmetic.modAdd_spec
#print axioms ECDSAAdd.Arithmetic.modSub_spec
#print axioms ECDSAAdd.Arithmetic.modAdd_resources
#print axioms ECDSAAdd.Arithmetic.modSub_resources
#print axioms ECDSAAdd.Arithmetic.fieldAdd_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldSub_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldAdd_spec
#print axioms ECDSAAdd.Arithmetic.fieldSub_spec
#print axioms ECDSAAdd.Arithmetic.fieldAdd_resources
#print axioms ECDSAAdd.Arithmetic.fieldSub_resources
#print axioms ECDSAAdd.Arithmetic.modMul_zero_spec
#print axioms ECDSAAdd.Arithmetic.modMul_spec
#print axioms ECDSAAdd.Arithmetic.modMul_resources
#print axioms ECDSAAdd.Arithmetic.fieldMul_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldMul_spec
#print axioms ECDSAAdd.Arithmetic.fieldMul_resources
#print axioms ECDSAAdd.Arithmetic.cswap_spec
#print axioms ECDSAAdd.Arithmetic.cswap_resources
#print axioms ECDSAAdd.Arithmetic.shiftRight_spec
#print axioms ECDSAAdd.Arithmetic.shiftLeft_spec
#print axioms ECDSAAdd.Arithmetic.shiftRight_left_cancel
#print axioms ECDSAAdd.Arithmetic.shift_resources
#print axioms ECDSAAdd.Arithmetic.counterIncXor_spec
#print axioms ECDSAAdd.Arithmetic.counterDecXor_spec
#print axioms ECDSAAdd.Arithmetic.counterXor_resources
#print axioms ECDSAAdd.Arithmetic.counterInc_spec
#print axioms ECDSAAdd.Arithmetic.counterDec_spec
#print axioms ECDSAAdd.Arithmetic.counter_resources
#print axioms ECDSAAdd.Arithmetic.addInPlace_spec
#print axioms ECDSAAdd.Arithmetic.subInPlace_spec
#print axioms ECDSAAdd.Arithmetic.addInPlace_resources
#print axioms ECDSAAdd.Arithmetic.maskedAddConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedSubConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.maskedSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.compareLt_spec
#print axioms ECDSAAdd.Arithmetic.maskedCompareLt_spec
#print axioms ECDSAAdd.Arithmetic.compareLtConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedCompareLtConst_spec
#print axioms ECDSAAdd.Arithmetic.compareLt_resources
#print axioms ECDSAAdd.halveMod_eq
#print axioms ECDSAAdd.halve_parity
#print axioms ECDSAAdd.double_flag
#print axioms ECDSAAdd.kaliski_unstep_step
#print axioms ECDSAAdd.kaliski_round_active
#print axioms ECDSAAdd.Arithmetic.recordRound_spec
#print axioms ECDSAAdd.Arithmetic.recordRound_preserves
#print axioms ECDSAAdd.Arithmetic.recordRound_counts
#print axioms ECDSAAdd.Arithmetic.recordRound_qubits
#print axioms ECDSAAdd.Arithmetic.recordRound_wires
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_spec
#print axioms ECDSAAdd.Arithmetic.kaliskiUnround_spec
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_counts
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_wires
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_qubits
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_257_resources
#print axioms ECDSAAdd.Arithmetic.fieldInverse_spec
#print axioms ECDSAAdd.Arithmetic.fieldInverse_xor_spec
#print axioms ECDSAAdd.Arithmetic.fieldInverse_wires
#print axioms ECDSAAdd.Arithmetic.fieldInverse_resources
#print axioms ECDSAAdd.Arithmetic.fieldInverse_contract
#print axioms ECDSAAdd.Arithmetic.inverseLoop_spec
#print axioms ECDSAAdd.Arithmetic.inverseLoop_xor_spec
#print axioms ECDSAAdd.Arithmetic.inverseLoop_wires
#print axioms ECDSAAdd.Arithmetic.inverseLoop_resources
#print axioms ECDSAAdd.Arithmetic.inverseLoop_257_resources
#print axioms ECDSAAdd.Arithmetic.kaliskiLoop_correct
#print axioms ECDSAAdd.Arithmetic.kaliskiLoop_qubits
#print axioms ECDSAAdd.Arithmetic.halveStep_spec
#print axioms ECDSAAdd.Arithmetic.doubleStep_spec
#print axioms ECDSAAdd.Arithmetic.halveInPlace_spec
#print axioms ECDSAAdd.Arithmetic.restoreInPlace_spec
#print axioms ECDSAAdd.Arithmetic.halveStep_counts
#print axioms ECDSAAdd.Arithmetic.halveInPlace_counts
#print axioms ECDSAAdd.Arithmetic.halveStep_wires
#print axioms ECDSAAdd.Arithmetic.halveInPlace_wires
#print axioms ECDSAAdd.Arithmetic.inversePrepare_spec
#print axioms ECDSAAdd.Arithmetic.inverseRestore_spec
#print axioms ECDSAAdd.Arithmetic.negativeInit_spec
#print axioms ECDSAAdd.kaliski_invariant
#print axioms ECDSAAdd.Arithmetic.equalConstant_correct
#print axioms ECDSAAdd.Arithmetic.equalConstant_counts
#print axioms ECDSAAdd.Arithmetic.equalConstant_wires
#print axioms ECDSAAdd.Arithmetic.pointBranchFlags_correct
#print axioms ECDSAAdd.Arithmetic.pointBranchFlags_counts
#print axioms ECDSAAdd.Arithmetic.safeDivisor_correct
#print axioms ECDSAAdd.Arithmetic.safeDivisor_counts
#print axioms ECDSAAdd.Arithmetic.PointAddLayout.allocated_length
#print axioms ECDSAAdd.Arithmetic.poolSub_work
#print axioms ECDSAAdd.Arithmetic.poolMul_work
#print axioms ECDSAAdd.Arithmetic.poolInverse_work_perm
#print axioms ECDSAAdd.Arithmetic.PointAddLayout.candidate_interfaces_nodup
#print axioms ECDSAAdd.Arithmetic.pointCandidate_zero_spec
#print axioms ECDSAAdd.Arithmetic.pointCandidate_cleanup_spec
#print axioms ECDSAAdd.Arithmetic.pointCandidate_counts
#print axioms ECDSAAdd.Arithmetic.candidateResult_coordinates
#print axioms ECDSAAdd.Arithmetic.pointCandidateValues_generic
#print axioms ECDSAAdd.Arithmetic.maskedConstant_correct
#print axioms ECDSAAdd.Arithmetic.point_classification
#print axioms ECDSAAdd.Arithmetic.pointFlagsCompute_correct
#print axioms ECDSAAdd.Arithmetic.pointFlagsClear_correct
#print axioms ECDSAAdd.Arithmetic.pointFlags_counts
#print axioms ECDSAAdd.Arithmetic.pointCandidate_support
#print axioms ECDSAAdd.Arithmetic.pointOutput_correct
#print axioms ECDSAAdd.Arithmetic.pointAddOut_spec
#print axioms ECDSAAdd.Arithmetic.pointAddOut_xor_spec
#print axioms ECDSAAdd.Arithmetic.pointAddOut_support
#print axioms ECDSAAdd.Arithmetic.pointAddOut_finite_resources
#print axioms ECDSAAdd.Arithmetic.pointAddOut_zero_resources
#print axioms ECDSAAdd.Arithmetic.pointSelectors_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointOutput_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_finite_ready
#print axioms ECDSAAdd.Arithmetic.controlledPointSwap_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_spec
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_support
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_finite_resources
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_finite_resources
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_zero_resources
#print axioms ECDSAAdd.kaliski_terminates
#print axioms ECDSAAdd.kaliski_register_bounds
#print axioms ECDSAAdd.halve_mod_correct
#print axioms ECDSAAdd.halveFixed_correct
#print axioms ECDSAAdd.kaliski_correct
#print axioms ECDSAAdd.kaliski_inverse_p
#print axioms ECDSAAdd.Secp256k1.p_prime
#print axioms ECDSAAdd.Secp256k1.G_ne_zero
#print axioms ECDSAAdd.Secp256k1.affineAdd_correct
LEAN
)
printf '%s\n' "$axioms"
printf '%s\n' "$axioms" | awk '
/depends on axioms:/ {
  sub(/^.*\[/, ""); sub(/\].*$/, "")
  n = split($0, names, /, */)
  for (i = 1; i <= n; i++)
    if (names[i] != "propext" && names[i] != "Classical.choice" && names[i] != "Quot.sound") exit 1
}'
