#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
lake --wfail build

# Report and check only the public proof entry points.
axioms=$(lake env lean /dev/stdin <<'LEAN'
import ECDSAAdd
#print axioms ECDSAAdd.andComputeErase_spec
#print axioms ECDSAAdd.andComputeErase_correct
#print axioms ECDSAAdd.andComputeErase_toffoliCount
#print axioms ECDSAAdd.andComputeErase_measurementCount
#print axioms ECDSAAdd.andComputeErase_qubitCount
#print axioms ECDSAAdd.Triple.seq
#print axioms ECDSAAdd.Triple.conseq
#print axioms ECDSAAdd.Triple.frame
#print axioms ECDSAAdd.Arithmetic.fullAdder_spec
#print axioms ECDSAAdd.Arithmetic.eraseCarry_spec
#print axioms ECDSAAdd.Arithmetic.notRegister_spec
#print axioms ECDSAAdd.Arithmetic.add_spec
#print axioms ECDSAAdd.Arithmetic.sub_spec
#print axioms ECDSAAdd.Arithmetic.add_erase_spec
#print axioms ECDSAAdd.Arithmetic.sub_erase_spec
#print axioms ECDSAAdd.Arithmetic.add_twice_spec
#print axioms ECDSAAdd.Arithmetic.add_resources
#print axioms ECDSAAdd.Arithmetic.sub_resources
#print axioms ECDSAAdd.Arithmetic.modAdd_spec
#print axioms ECDSAAdd.Arithmetic.modSub_spec
#print axioms ECDSAAdd.Arithmetic.modAdd_resources
#print axioms ECDSAAdd.Arithmetic.modSub_resources
#print axioms ECDSAAdd.Arithmetic.fieldAdd_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldSub_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldAdd_spec
#print axioms ECDSAAdd.Arithmetic.fieldSub_spec
#print axioms ECDSAAdd.Arithmetic.fieldAdd_resources
#print axioms ECDSAAdd.Arithmetic.fieldSub_resources
#print axioms ECDSAAdd.Arithmetic.fieldMul_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldMul_spec
#print axioms ECDSAAdd.Arithmetic.fieldMul_resources
#print axioms ECDSAAdd.Arithmetic.cswap_spec
#print axioms ECDSAAdd.Arithmetic.cswap_resources
#print axioms ECDSAAdd.Arithmetic.shiftRight_spec
#print axioms ECDSAAdd.Arithmetic.shiftLeft_spec
#print axioms ECDSAAdd.Arithmetic.shiftRight_left_cancel
#print axioms ECDSAAdd.Arithmetic.shift_resources
#print axioms ECDSAAdd.Arithmetic.counterIncXor_spec
#print axioms ECDSAAdd.Arithmetic.counterDecXor_spec
#print axioms ECDSAAdd.Arithmetic.counterXor_resources
#print axioms ECDSAAdd.Arithmetic.counterInc_spec
#print axioms ECDSAAdd.Arithmetic.counterDec_spec
#print axioms ECDSAAdd.Arithmetic.counter_resources
#print axioms ECDSAAdd.Arithmetic.addInPlace_spec
#print axioms ECDSAAdd.Arithmetic.subInPlace_spec
#print axioms ECDSAAdd.Arithmetic.addInPlace_resources
#print axioms ECDSAAdd.Arithmetic.maskedAddConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedSubConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.maskedSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.zeroControlled_correct
#print axioms ECDSAAdd.Arithmetic.zeroControlled_spec
#print axioms ECDSAAdd.Arithmetic.zeroControlled_resources
#print axioms ECDSAAdd.Arithmetic.maskedInPlace_counts
#print axioms ECDSAAdd.Arithmetic.maskedInPlace_wires
#print axioms ECDSAAdd.Arithmetic.poolInverse_used_perm
#print axioms ECDSAAdd.Arithmetic.poolInverseUsedWork_length
#print axioms ECDSAAdd.Arithmetic.compareLt_spec
#print axioms ECDSAAdd.Arithmetic.maskedCompareLt_spec
#print axioms ECDSAAdd.Arithmetic.compareLtConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedCompareLtConst_spec
#print axioms ECDSAAdd.Arithmetic.compareLt_resources
#print axioms ECDSAAdd.Arithmetic.modAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.modAddInPlace_frame
#print axioms ECDSAAdd.Arithmetic.modAddInPlace_resources
#print axioms ECDSAAdd.Arithmetic.modSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.modSubInPlace_frame
#print axioms ECDSAAdd.Arithmetic.modSubInPlace_resources
#print axioms ECDSAAdd.Arithmetic.controlledModAdd_spec
#print axioms ECDSAAdd.Arithmetic.controlledModAdd_frame
#print axioms ECDSAAdd.Arithmetic.controlledModAdd_resources
#print axioms ECDSAAdd.Arithmetic.controlledModSub_spec
#print axioms ECDSAAdd.Arithmetic.controlledModSub_frame
#print axioms ECDSAAdd.Arithmetic.controlledModSub_resources
#print axioms ECDSAAdd.Arithmetic.rotateRight_spec
#print axioms ECDSAAdd.Arithmetic.rotateLeft_spec
#print axioms ECDSAAdd.Arithmetic.rotate_frame
#print axioms ECDSAAdd.Arithmetic.rotate_wires
#print axioms ECDSAAdd.Arithmetic.rotate_counts
#print axioms ECDSAAdd.Arithmetic.halfInPlace_spec
#print axioms ECDSAAdd.Arithmetic.dblInPlace_spec
#print axioms ECDSAAdd.Arithmetic.modUnary_frame
#print axioms ECDSAAdd.Arithmetic.modUnary_wires
#print axioms ECDSAAdd.Arithmetic.modUnary_resources
#print axioms ECDSAAdd.Arithmetic.candidatePool_union
#print axioms ECDSAAdd.Arithmetic.candidatePool_length
#print axioms ECDSAAdd.halveMod_eq
#print axioms ECDSAAdd.halve_parity
#print axioms ECDSAAdd.double_flag
#print axioms ECDSAAdd.kaliski_unstep_step
#print axioms ECDSAAdd.kaliski_round_active
#print axioms ECDSAAdd.Arithmetic.recordRound_spec
#print axioms ECDSAAdd.Arithmetic.recordRound_preserves
#print axioms ECDSAAdd.Arithmetic.recordRound_counts
#print axioms ECDSAAdd.Arithmetic.recordRound_qubits
#print axioms ECDSAAdd.Arithmetic.recordRound_wires
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_spec
#print axioms ECDSAAdd.Arithmetic.kaliskiUnround_spec
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_counts
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_wires
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_qubits
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_257_resources
#print axioms ECDSAAdd.Arithmetic.fieldInverse_spec
#print axioms ECDSAAdd.Arithmetic.fieldInverse_xor_spec
#print axioms ECDSAAdd.Arithmetic.fieldInverse_wires
#print axioms ECDSAAdd.Arithmetic.fieldInverse_resources
#print axioms ECDSAAdd.Arithmetic.fieldInverse_contract
#print axioms ECDSAAdd.Arithmetic.inverseLoop_spec
#print axioms ECDSAAdd.Arithmetic.inverseLoop_xor_spec
#print axioms ECDSAAdd.Arithmetic.inverseLoop_wires
#print axioms ECDSAAdd.Arithmetic.inverseLoop_resources
#print axioms ECDSAAdd.Arithmetic.inverseLoop_257_resources
#print axioms ECDSAAdd.Arithmetic.kaliskiLoop_correct
#print axioms ECDSAAdd.Arithmetic.kaliskiLoop_qubits
#print axioms ECDSAAdd.Arithmetic.halveStep_spec
#print axioms ECDSAAdd.Arithmetic.doubleStep_spec
#print axioms ECDSAAdd.Arithmetic.halveInPlace_spec
#print axioms ECDSAAdd.Arithmetic.restoreInPlace_spec
#print axioms ECDSAAdd.Arithmetic.halveStep_counts
#print axioms ECDSAAdd.Arithmetic.halveInPlace_counts
#print axioms ECDSAAdd.Arithmetic.halveStep_wires
#print axioms ECDSAAdd.Arithmetic.halveInPlace_wires
#print axioms ECDSAAdd.Arithmetic.inversePrepare_spec
#print axioms ECDSAAdd.Arithmetic.inverseRestore_spec
#print axioms ECDSAAdd.Arithmetic.negativeInit_spec
#print axioms ECDSAAdd.kaliski_invariant
#print axioms ECDSAAdd.Arithmetic.equalConstant_correct
#print axioms ECDSAAdd.Arithmetic.equalConstant_counts
#print axioms ECDSAAdd.Arithmetic.equalConstant_wires
#print axioms ECDSAAdd.Arithmetic.pointBranchFlags_correct
#print axioms ECDSAAdd.Arithmetic.pointBranchFlags_counts
#print axioms ECDSAAdd.Arithmetic.safeDivisor_correct
#print axioms ECDSAAdd.Arithmetic.safeDivisor_counts
#print axioms ECDSAAdd.Arithmetic.PointAddLayout.allocated_length
#print axioms ECDSAAdd.Arithmetic.poolSub_work
#print axioms ECDSAAdd.Arithmetic.poolMul_work
#print axioms ECDSAAdd.Arithmetic.poolInverse_work_perm
#print axioms ECDSAAdd.Arithmetic.PointAddLayout.candidate_interfaces_nodup
#print axioms ECDSAAdd.Arithmetic.pointCandidate_zero_spec
#print axioms ECDSAAdd.Arithmetic.pointCandidate_cleanup_spec
#print axioms ECDSAAdd.Arithmetic.pointCandidate_counts
#print axioms ECDSAAdd.Arithmetic.candidateResult_coordinates
#print axioms ECDSAAdd.Arithmetic.pointCandidateValues_generic
#print axioms ECDSAAdd.Arithmetic.maskedConstant_correct
#print axioms ECDSAAdd.Arithmetic.point_classification
#print axioms ECDSAAdd.Arithmetic.pointFlagsCompute_correct
#print axioms ECDSAAdd.Arithmetic.pointFlagsClear_correct
#print axioms ECDSAAdd.Arithmetic.pointFlags_counts
#print axioms ECDSAAdd.Arithmetic.pointCandidate_support
#print axioms ECDSAAdd.Arithmetic.pointOutput_correct
#print axioms ECDSAAdd.Arithmetic.pointAddOut_spec
#print axioms ECDSAAdd.Arithmetic.pointAddOut_xor_spec
#print axioms ECDSAAdd.Arithmetic.pointAddOut_support
#print axioms ECDSAAdd.Arithmetic.pointAddOut_finite_resources
#print axioms ECDSAAdd.Arithmetic.pointAddOut_zero_resources
#print axioms ECDSAAdd.Arithmetic.pointSelectors_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointOutput_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_finite_ready
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_spec
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_support
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_finite_resources
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_finite_resources
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_zero_resources
#print axioms ECDSAAdd.kaliski_terminates
#print axioms ECDSAAdd.kaliski_register_bounds
#print axioms ECDSAAdd.halve_mod_correct
#print axioms ECDSAAdd.halveFixed_correct
#print axioms ECDSAAdd.kaliski_correct
#print axioms ECDSAAdd.kaliski_inverse_p
#print axioms ECDSAAdd.montgomeryStep_exact
#print axioms ECDSAAdd.montgomeryStep_bound
#print axioms ECDSAAdd.montgomeryStep_restore
#print axioms ECDSAAdd.montgomery_normalize
#print axioms ECDSAAdd.montgomeryValue_bound
#print axioms ECDSAAdd.montgomeryValue_invariant
#print axioms ECDSAAdd.montgomeryValue_finish
#print axioms ECDSAAdd.montgomery_standard_conversion
#print axioms ECDSAAdd.Arithmetic.lookup_spec
#print axioms ECDSAAdd.Arithmetic.lookup_frame
#print axioms ECDSAAdd.Arithmetic.lookup_counts
#print axioms ECDSAAdd.Arithmetic.lookup_wires_subset
#print axioms ECDSAAdd.Secp256k1.p_prime
#print axioms ECDSAAdd.Secp256k1.G_ne_zero
#print axioms ECDSAAdd.Secp256k1.affineAdd_correct
#print axioms ECDSAAdd.Secp256k1.sameX_iff_eq_or_neg
#print axioms ECDSAAdd.Secp256k1.ordinary_point_iff
#print axioms ECDSAAdd.Secp256k1.doubling_enabled_iff
#print axioms ECDSAAdd.Secp256k1.translated_point_flags
#print axioms ECDSAAdd.Secp256k1.generic_inplace_values
#print axioms ECDSAAdd.Secp256k1.second_denominator_zero_iff
#print axioms ECDSAAdd.Secp256k1.exceptional_slope_eq
#print axioms ECDSAAdd.Secp256k1.slope_from_output
#print axioms ECDSAAdd.Arithmetic.divideLoad_values
#print axioms ECDSAAdd.Arithmetic.divideProduct_correct
#print axioms ECDSAAdd.Arithmetic.divideAdd_spec
#print axioms ECDSAAdd.Arithmetic.divideSub_spec
#print axioms ECDSAAdd.Arithmetic.divide_frame
#print axioms ECDSAAdd.Arithmetic.divide_counts
#print axioms ECDSAAdd.Arithmetic.divide_wires
#print axioms ECDSAAdd.Arithmetic.divide_qubits
#print axioms ECDSAAdd.Arithmetic.pointCode_injective
#print axioms ECDSAAdd.Arithmetic.pointInPlaceNegate_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceSquare_correct
#print axioms ECDSAAdd.Arithmetic.pointInPlaceClearSlope_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceGeneric_point
#print axioms ECDSAAdd.Arithmetic.pointInPlaceCorners_effect
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_frame
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_full_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_counts
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_wires
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_qubits
#print axioms ECDSAAdd.montgomery_two_stages
#print axioms ECDSAAdd.Arithmetic.rotateRightBits_spec
#print axioms ECDSAAdd.Arithmetic.rotateLeftBits_spec
#print axioms ECDSAAdd.Arithmetic.montNormalize_correct
#print axioms ECDSAAdd.Arithmetic.montDenormalize_correct
#print axioms ECDSAAdd.Arithmetic.montPrepare_spec
#print axioms ECDSAAdd.Arithmetic.montRestore_spec
#print axioms ECDSAAdd.Arithmetic.constPrepare_spec
#print axioms ECDSAAdd.Arithmetic.constRestore_spec
#print axioms ECDSAAdd.Arithmetic.montP_correct
#print axioms ECDSAAdd.Arithmetic.montQ_correct
#print axioms ECDSAAdd.Arithmetic.montP_spec
#print axioms ECDSAAdd.Arithmetic.montQ_spec
#print axioms ECDSAAdd.Arithmetic.montPQ_counts
#print axioms ECDSAAdd.Arithmetic.montPQ_wires
#print axioms ECDSAAdd.Arithmetic.montPQ_resources
#print axioms ECDSAAdd.Arithmetic.montMulXor_spec
#print axioms ECDSAAdd.Arithmetic.montMulAdd_spec
#print axioms ECDSAAdd.Arithmetic.montMulSub_spec
#print axioms ECDSAAdd.Arithmetic.montMulControlledAdd_spec
#print axioms ECDSAAdd.Arithmetic.montMulControlledSub_spec
#print axioms ECDSAAdd.Arithmetic.montMulXor_frame
#print axioms ECDSAAdd.Arithmetic.montMulAdd_frame
#print axioms ECDSAAdd.Arithmetic.montMulSub_frame
#print axioms ECDSAAdd.Arithmetic.montMulControlledAdd_frame
#print axioms ECDSAAdd.Arithmetic.montMulControlledSub_frame
#print axioms ECDSAAdd.Arithmetic.montAdapter_counts
#print axioms ECDSAAdd.Arithmetic.montControlledAdapter_counts
#print axioms ECDSAAdd.Arithmetic.montAdapter_wires
#print axioms ECDSAAdd.Arithmetic.montControlledAdapter_wires
#print axioms ECDSAAdd.Arithmetic.montAdapter_qubits
#print axioms ECDSAAdd.Arithmetic.montControlledAdapter_qubits
#print axioms ECDSAAdd.Arithmetic.eraseMask_correct
#print axioms ECDSAAdd.Arithmetic.measuredMaskedAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.measuredMaskedSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.measuredMaskedAddInPlace_frame
#print axioms ECDSAAdd.Arithmetic.measuredMaskedSubInPlace_frame
#print axioms ECDSAAdd.Arithmetic.measuredMaskedInPlace_counts
#print axioms ECDSAAdd.Arithmetic.measuredMaskedInPlace_wires
#print axioms ECDSAAdd.Arithmetic.measuredMaskedInPlace_qubits
#print axioms ECDSAAdd.Arithmetic.lookup10_spec
#print axioms ECDSAAdd.Arithmetic.lookup10_counts
#print axioms ECDSAAdd.Arithmetic.lookup10_core_wires
#print axioms ECDSAAdd.Arithmetic.lookup10_frame
#print axioms ECDSAAdd.inverseScaleFactor_bound
#print axioms ECDSAAdd.inverseScaleFactor_relation
#print axioms ECDSAAdd.montgomery_inverseScaleFactor
#print axioms ECDSAAdd.inverseScaleFactor_halving
#print axioms ECDSAAdd.kaliski_scale_count
#print axioms ECDSAAdd.kaliski_montgomery_scale
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.prepare_spec
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.restore_spec
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.prepare_frame
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.restore_frame
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.wires_subset
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.counts
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_widths
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_work
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_live
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaleLive_subset
#print axioms ECDSAAdd.Arithmetic.compactScale_values
#print axioms ECDSAAdd.Arithmetic.InverseScaledMiddle.congr
#print axioms ECDSAAdd.Arithmetic.compactConstants_values
#print axioms ECDSAAdd.Arithmetic.compactNeg_values
#print axioms ECDSAAdd.Arithmetic.compactReady_iff
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.work_covered
#print axioms ECDSAAdd.kaliski_terminal_even
#print axioms ECDSAAdd.kaliski_terminal_values
#print axioms ECDSAAdd.negative_even_value
#print axioms ECDSAAdd.negative_even_restore
#print axioms ECDSAAdd.Arithmetic.negativeEven_correct
#print axioms ECDSAAdd.Arithmetic.negativeEven_spec
#print axioms ECDSAAdd.Arithmetic.negativeEven_counts
#print axioms ECDSAAdd.Arithmetic.negativeEven_wires

#print axioms ECDSAAdd.kaliski_swap_from_r
#print axioms ECDSAAdd.Arithmetic.recoverSwap_state
#print axioms ECDSAAdd.Arithmetic.oneBitRound_spec
#print axioms ECDSAAdd.Arithmetic.oneBitUnround_spec
#print axioms ECDSAAdd.Arithmetic.oneBitRound_counts
#print axioms ECDSAAdd.Arithmetic.oneBitRound_wires
#print axioms ECDSAAdd.Arithmetic.oneBitRound_preserves
#print axioms ECDSAAdd.Arithmetic.oneBitRound_qubits
#print axioms ECDSAAdd.Arithmetic.oneBitLoop_correct
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_correct
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_counts
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_wires
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_qubits
#print axioms ECDSAAdd.Arithmetic.OneBitRecordsValues.zero_iff
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactBorrow_length
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.idleBorrow_length
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compact_parts_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compact_inputs_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactCore_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactCore_length
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.idleBorrow_subset
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_widths
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_work
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_live
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactNeg_widths
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactNeg_partition
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactNeg_nodup
#print axioms ECDSAAdd.Arithmetic.terminalConstants_correct
#print axioms ECDSAAdd.Arithmetic.terminalConstants_spec
#print axioms ECDSAAdd.Arithmetic.terminalConstants_resources
#print axioms ECDSAAdd.Arithmetic.square_sum128_bound
#print axioms ECDSAAdd.Arithmetic.square_sum128_square_bound
#print axioms ECDSAAdd.Arithmetic.triangularSquare_correct
#print axioms ECDSAAdd.Arithmetic.triangularSquare_spec
#print axioms ECDSAAdd.Arithmetic.triangularSquareClear_spec
#print axioms ECDSAAdd.Arithmetic.triangularSquare_frame
#print axioms ECDSAAdd.Arithmetic.triangularSquareClear_frame
#print axioms ECDSAAdd.Arithmetic.triangularSquare_counts
#print axioms ECDSAAdd.Arithmetic.triangularSquare_wires
#print axioms ECDSAAdd.Arithmetic.SquareReduction.reduced_square_word
#print axioms ECDSAAdd.Arithmetic.squareFold_correct
#print axioms ECDSAAdd.Arithmetic.squareFold_counts
#print axioms ECDSAAdd.Arithmetic.squareFold_wires_subset
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_spec
#print axioms ECDSAAdd.Arithmetic.karatsubaSquareClear_spec
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_frame
#print axioms ECDSAAdd.Arithmetic.karatsubaSquareClear_frame
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_counts
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_wires_subset
#print axioms ECDSAAdd.Arithmetic.squareReduce_correct
#print axioms ECDSAAdd.Arithmetic.squareReduce_frame
#print axioms ECDSAAdd.Arithmetic.squareReduce_counts
#print axioms ECDSAAdd.Arithmetic.squareReduce_wires_subset
#print axioms ECDSAAdd.Arithmetic.squareSub_spec
#print axioms ECDSAAdd.Arithmetic.squareSub_frame
#print axioms ECDSAAdd.Arithmetic.squareSub_counts
#print axioms ECDSAAdd.Arithmetic.squareSub_wires_subset
#print axioms ECDSAAdd.Arithmetic.SquareSubLayout.work_length
#print axioms ECDSAAdd.Arithmetic.SquareSubLayout.fromPool_work
#print axioms ECDSAAdd.Arithmetic.SquareSubLayout.fromPool_nodup
#print axioms ECDSAAdd.Arithmetic.squareSub_correct
#print axioms ECDSAAdd.Arithmetic.pointInPlaceSquare_correct
LEAN
)
printf '%s\n' "$axioms"
printf '%s\n' "$axioms" | awk '
/depends on axioms:/ {
  sub(/^.*\[/, ""); sub(/\].*$/, "")
  n = split($0, names, /, */)
  for (i = 1; i <= n; i++)
    if (names[i] != "propext" && names[i] != "Classical.choice" && names[i] != "Quot.sound") exit 1
}'
