#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
lake --wfail build

# Report and check only the public proof entry points.
set +e
axioms=$(lake env lean /dev/stdin <<'LEAN'
import ECDSAAdd
import ECDSAAdd.Arithmetic.OffsetBorrowedCanonicalReplay
import ECDSAAdd.Arithmetic.OffsetBorrowedInverseCanonicalReplay
import ECDSAAdd.Arithmetic.OffsetBorrowedSharedDivision
import ECDSAAdd.Arithmetic.OffsetBorrowedInverseSharedMultiplication
import ECDSAAdd.Arithmetic.OffsetBorrowedDirectArithmetic
import ECDSAAdd.Arithmetic.OffsetBorrowedControlledPort
import ECDSAAdd.Arithmetic.OffsetBorrowedSupportPoint
import ECDSAAdd.Arithmetic.DisjointPrograms
import ECDSAAdd.Arithmetic.CompressedSkywalkLayout
import ECDSAAdd.Arithmetic.CompressedSkywalkLoop
import ECDSAAdd.Arithmetic.CompressedSkywalkSchedule
import ECDSAAdd.Arithmetic.CompressedSkywalkPrefix
import ECDSAAdd.Arithmetic.CompressedSkywalkForward
import ECDSAAdd.Arithmetic.CompressedSkywalkDecode
import ECDSAAdd.Arithmetic.CompressedSkywalkReverse
import ECDSAAdd.Arithmetic.CompressedSkywalkRestore
import ECDSAAdd.Arithmetic.TranscriptSelectFlag
import ECDSAAdd.Arithmetic.DirectZeroDivisor
import ECDSAAdd.Arithmetic.DirectZeroControlled
import ECDSAAdd.Arithmetic.MixedTranscriptFieldCell
import ECDSAAdd.Arithmetic.MixedTranscriptReplay
import ECDSAAdd.Arithmetic.MixedTranscriptDivision
import ECDSAAdd.Arithmetic.MixedTranscriptMultiplication
import ECDSAAdd.Arithmetic.SkywalkDirectPointLayout
import ECDSAAdd.Arithmetic.DirectSkywalkInput
import ECDSAAdd.Arithmetic.DirectSkywalkCleanup
import ECDSAAdd.Arithmetic.DirectSkywalkArithmetic
import ECDSAAdd.Arithmetic.DirectSkywalkControlledPort
import ECDSAAdd.Arithmetic.DirectSkywalkFieldSupport
import ECDSAAdd.Arithmetic.DirectSkywalkKernelSupport
import ECDSAAdd.Arithmetic.DirectSkywalkSupport
import ECDSAAdd.Arithmetic.FusedInversePackedProof
import ECDSAAdd.Arithmetic.BalancedIntegratedAudit
import ECDSAAdd.Arithmetic.CompactIntegratedAudit
#print axioms ECDSAAdd.andComputeErase_spec
#print axioms ECDSAAdd.andComputeErase_correct
#print axioms ECDSAAdd.andComputeErase_toffoliCount
#print axioms ECDSAAdd.andComputeErase_measurementCount
#print axioms ECDSAAdd.andComputeErase_qubitCount
#print axioms ECDSAAdd.Triple.seq
#print axioms ECDSAAdd.Triple.conseq
#print axioms ECDSAAdd.Triple.frame
#print axioms ECDSAAdd.Arithmetic.fullAdder_spec
#print axioms ECDSAAdd.Arithmetic.eraseCarry_spec
#print axioms ECDSAAdd.Arithmetic.notRegister_spec
#print axioms ECDSAAdd.Arithmetic.add_spec
#print axioms ECDSAAdd.Arithmetic.sub_spec
#print axioms ECDSAAdd.Arithmetic.add_erase_spec
#print axioms ECDSAAdd.Arithmetic.sub_erase_spec
#print axioms ECDSAAdd.Arithmetic.add_twice_spec
#print axioms ECDSAAdd.Arithmetic.add_resources
#print axioms ECDSAAdd.Arithmetic.sub_resources
#print axioms ECDSAAdd.Arithmetic.modAdd_spec
#print axioms ECDSAAdd.Arithmetic.modSub_spec
#print axioms ECDSAAdd.Arithmetic.modAdd_resources
#print axioms ECDSAAdd.Arithmetic.modSub_resources
#print axioms ECDSAAdd.Arithmetic.fieldAdd_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldSub_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldAdd_spec
#print axioms ECDSAAdd.Arithmetic.fieldSub_spec
#print axioms ECDSAAdd.Arithmetic.fieldAdd_resources
#print axioms ECDSAAdd.Arithmetic.fieldSub_resources
#print axioms ECDSAAdd.Arithmetic.fieldMul_zero_spec
#print axioms ECDSAAdd.Arithmetic.fieldMul_spec
#print axioms ECDSAAdd.Arithmetic.fieldMul_resources
#print axioms ECDSAAdd.Arithmetic.cswap_spec
#print axioms ECDSAAdd.Arithmetic.cswap_resources
#print axioms ECDSAAdd.Arithmetic.shiftRight_spec
#print axioms ECDSAAdd.Arithmetic.shiftLeft_spec
#print axioms ECDSAAdd.Arithmetic.shiftRight_left_cancel
#print axioms ECDSAAdd.Arithmetic.shift_resources
#print axioms ECDSAAdd.Arithmetic.counterIncXor_spec
#print axioms ECDSAAdd.Arithmetic.counterDecXor_spec
#print axioms ECDSAAdd.Arithmetic.counterXor_resources
#print axioms ECDSAAdd.Arithmetic.counterInc_spec
#print axioms ECDSAAdd.Arithmetic.counterDec_spec
#print axioms ECDSAAdd.Arithmetic.counter_resources
#print axioms ECDSAAdd.Arithmetic.addInPlace_spec
#print axioms ECDSAAdd.Arithmetic.subInPlace_spec
#print axioms ECDSAAdd.Arithmetic.addInPlace_resources
#print axioms ECDSAAdd.Arithmetic.maskedAddConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedSubConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.maskedSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.zeroControlled_correct
#print axioms ECDSAAdd.Arithmetic.zeroControlled_spec
#print axioms ECDSAAdd.Arithmetic.zeroControlled_resources
#print axioms ECDSAAdd.Arithmetic.maskedInPlace_counts
#print axioms ECDSAAdd.Arithmetic.maskedInPlace_wires
#print axioms ECDSAAdd.Arithmetic.poolInverse_used_perm
#print axioms ECDSAAdd.Arithmetic.poolInverseUsedWork_length
#print axioms ECDSAAdd.Arithmetic.compareLt_spec
#print axioms ECDSAAdd.Arithmetic.maskedCompareLt_spec
#print axioms ECDSAAdd.Arithmetic.compareLtConst_spec
#print axioms ECDSAAdd.Arithmetic.maskedCompareLtConst_spec
#print axioms ECDSAAdd.Arithmetic.compareLt_resources
#print axioms ECDSAAdd.Arithmetic.modAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.modAddInPlace_frame
#print axioms ECDSAAdd.Arithmetic.modAddInPlace_resources
#print axioms ECDSAAdd.Arithmetic.modSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.modSubInPlace_frame
#print axioms ECDSAAdd.Arithmetic.modSubInPlace_resources
#print axioms ECDSAAdd.Arithmetic.controlledModAdd_spec
#print axioms ECDSAAdd.Arithmetic.controlledModAdd_frame
#print axioms ECDSAAdd.Arithmetic.controlledModAdd_resources
#print axioms ECDSAAdd.Arithmetic.controlledModSub_spec
#print axioms ECDSAAdd.Arithmetic.controlledModSub_frame
#print axioms ECDSAAdd.Arithmetic.controlledModSub_resources
#print axioms ECDSAAdd.Arithmetic.measuredControlledModAdd_spec
#print axioms ECDSAAdd.Arithmetic.measuredControlledModAdd_frame
#print axioms ECDSAAdd.Arithmetic.measuredControlledModAdd_wires
#print axioms ECDSAAdd.Arithmetic.measuredControlledModAdd_resources
#print axioms ECDSAAdd.Arithmetic.measuredControlledModSub_spec
#print axioms ECDSAAdd.Arithmetic.measuredControlledModSub_frame
#print axioms ECDSAAdd.Arithmetic.measuredControlledModSub_wires
#print axioms ECDSAAdd.Arithmetic.measuredControlledModSub_resources
#print axioms ECDSAAdd.Arithmetic.rotateRight_spec
#print axioms ECDSAAdd.Arithmetic.rotateLeft_spec
#print axioms ECDSAAdd.Arithmetic.rotate_frame
#print axioms ECDSAAdd.Arithmetic.rotate_wires
#print axioms ECDSAAdd.Arithmetic.rotate_counts
#print axioms ECDSAAdd.Arithmetic.halfInPlace_spec
#print axioms ECDSAAdd.Arithmetic.dblInPlace_spec
#print axioms ECDSAAdd.Arithmetic.modUnary_frame
#print axioms ECDSAAdd.Arithmetic.modUnary_wires
#print axioms ECDSAAdd.Arithmetic.modUnary_resources
#print axioms ECDSAAdd.Arithmetic.candidatePool_union
#print axioms ECDSAAdd.Arithmetic.candidatePool_length
#print axioms ECDSAAdd.halveMod_eq
#print axioms ECDSAAdd.halve_parity
#print axioms ECDSAAdd.double_flag
#print axioms ECDSAAdd.kaliski_unstep_step
#print axioms ECDSAAdd.kaliski_round_active
#print axioms ECDSAAdd.Arithmetic.recordRound_spec
#print axioms ECDSAAdd.Arithmetic.recordRound_preserves
#print axioms ECDSAAdd.Arithmetic.recordRound_counts
#print axioms ECDSAAdd.Arithmetic.recordRound_qubits
#print axioms ECDSAAdd.Arithmetic.recordRound_wires
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_spec
#print axioms ECDSAAdd.Arithmetic.kaliskiUnround_spec
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_counts
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_wires
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_qubits
#print axioms ECDSAAdd.Arithmetic.kaliskiRound_257_resources
#print axioms ECDSAAdd.Arithmetic.fieldInverse_spec
#print axioms ECDSAAdd.Arithmetic.fieldInverse_xor_spec
#print axioms ECDSAAdd.Arithmetic.fieldInverse_wires
#print axioms ECDSAAdd.Arithmetic.fieldInverse_resources
#print axioms ECDSAAdd.Arithmetic.fieldInverse_contract
#print axioms ECDSAAdd.Arithmetic.inverseLoop_spec
#print axioms ECDSAAdd.Arithmetic.inverseLoop_xor_spec
#print axioms ECDSAAdd.Arithmetic.inverseLoop_wires
#print axioms ECDSAAdd.Arithmetic.inverseLoop_resources
#print axioms ECDSAAdd.Arithmetic.inverseLoop_257_resources
#print axioms ECDSAAdd.Arithmetic.kaliskiLoop_correct
#print axioms ECDSAAdd.Arithmetic.kaliskiLoop_qubits
#print axioms ECDSAAdd.Arithmetic.halveStep_spec
#print axioms ECDSAAdd.Arithmetic.doubleStep_spec
#print axioms ECDSAAdd.Arithmetic.halveInPlace_spec
#print axioms ECDSAAdd.Arithmetic.restoreInPlace_spec
#print axioms ECDSAAdd.Arithmetic.halveStep_counts
#print axioms ECDSAAdd.Arithmetic.halveInPlace_counts
#print axioms ECDSAAdd.Arithmetic.halveStep_wires
#print axioms ECDSAAdd.Arithmetic.halveInPlace_wires
#print axioms ECDSAAdd.Arithmetic.inversePrepare_spec
#print axioms ECDSAAdd.Arithmetic.inverseRestore_spec
#print axioms ECDSAAdd.Arithmetic.negativeInit_spec
#print axioms ECDSAAdd.kaliski_invariant
#print axioms ECDSAAdd.Arithmetic.equalConstant_correct
#print axioms ECDSAAdd.Arithmetic.equalConstant_counts
#print axioms ECDSAAdd.Arithmetic.equalConstant_wires
#print axioms ECDSAAdd.Arithmetic.pointBranchFlags_correct
#print axioms ECDSAAdd.Arithmetic.pointBranchFlags_counts
#print axioms ECDSAAdd.Arithmetic.safeDivisor_correct
#print axioms ECDSAAdd.Arithmetic.safeDivisor_counts
#print axioms ECDSAAdd.Arithmetic.PointAddLayout.allocated_length
#print axioms ECDSAAdd.Arithmetic.poolSub_work
#print axioms ECDSAAdd.Arithmetic.poolMul_work
#print axioms ECDSAAdd.Arithmetic.poolInverse_work_perm
#print axioms ECDSAAdd.Arithmetic.PointAddLayout.candidate_interfaces_nodup
#print axioms ECDSAAdd.Arithmetic.pointCandidate_zero_spec
#print axioms ECDSAAdd.Arithmetic.pointCandidate_cleanup_spec
#print axioms ECDSAAdd.Arithmetic.pointCandidate_counts
#print axioms ECDSAAdd.Arithmetic.candidateResult_coordinates
#print axioms ECDSAAdd.Arithmetic.pointCandidateValues_generic
#print axioms ECDSAAdd.Arithmetic.maskedConstant_correct
#print axioms ECDSAAdd.Arithmetic.point_classification
#print axioms ECDSAAdd.Arithmetic.pointFlagsCompute_correct
#print axioms ECDSAAdd.Arithmetic.pointFlagsClear_correct
#print axioms ECDSAAdd.Arithmetic.pointFlags_counts
#print axioms ECDSAAdd.Arithmetic.pointCandidate_support
#print axioms ECDSAAdd.Arithmetic.pointOutput_correct
#print axioms ECDSAAdd.Arithmetic.pointAddOut_spec
#print axioms ECDSAAdd.Arithmetic.pointAddOut_xor_spec
#print axioms ECDSAAdd.Arithmetic.pointAddOut_support
#print axioms ECDSAAdd.Arithmetic.pointAddOut_finite_resources
#print axioms ECDSAAdd.Arithmetic.pointAddOut_zero_resources
#print axioms ECDSAAdd.Arithmetic.pointSelectors_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointOutput_correct
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_finite_ready
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_spec
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_support
#print axioms ECDSAAdd.Arithmetic.controlledPointAddOut_finite_resources
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_finite_resources
#print axioms ECDSAAdd.Arithmetic.controlledPointAdd_zero_resources
#print axioms ECDSAAdd.kaliski_terminates
#print axioms ECDSAAdd.kaliski_register_bounds
#print axioms ECDSAAdd.halve_mod_correct
#print axioms ECDSAAdd.halveFixed_correct
#print axioms ECDSAAdd.kaliski_correct
#print axioms ECDSAAdd.kaliski_inverse_p
#print axioms ECDSAAdd.montgomeryStep_exact
#print axioms ECDSAAdd.montgomeryStep_bound
#print axioms ECDSAAdd.montgomeryStep_restore
#print axioms ECDSAAdd.montgomery_normalize
#print axioms ECDSAAdd.montgomeryValue_bound
#print axioms ECDSAAdd.montgomeryValue_invariant
#print axioms ECDSAAdd.montgomeryValue_finish
#print axioms ECDSAAdd.montgomery_standard_conversion
#print axioms ECDSAAdd.Arithmetic.lookup_spec
#print axioms ECDSAAdd.Arithmetic.lookup_frame
#print axioms ECDSAAdd.Arithmetic.lookup_counts
#print axioms ECDSAAdd.Arithmetic.lookup_wires_subset
#print axioms ECDSAAdd.Secp256k1.p_prime
#print axioms ECDSAAdd.Secp256k1.G_ne_zero
#print axioms ECDSAAdd.Secp256k1.affineAdd_correct
#print axioms ECDSAAdd.Secp256k1.sameX_iff_eq_or_neg
#print axioms ECDSAAdd.Secp256k1.ordinary_point_iff
#print axioms ECDSAAdd.Secp256k1.doubling_enabled_iff
#print axioms ECDSAAdd.Secp256k1.translated_point_flags
#print axioms ECDSAAdd.Secp256k1.generic_inplace_values
#print axioms ECDSAAdd.Secp256k1.second_denominator_zero_iff
#print axioms ECDSAAdd.Secp256k1.exceptional_slope_eq
#print axioms ECDSAAdd.Secp256k1.slope_from_output
#print axioms ECDSAAdd.Arithmetic.divideLoad_values
#print axioms ECDSAAdd.Arithmetic.divideProduct_correct
#print axioms ECDSAAdd.Arithmetic.divideAdd_spec
#print axioms ECDSAAdd.Arithmetic.divideSub_spec
#print axioms ECDSAAdd.Arithmetic.divide_frame
#print axioms ECDSAAdd.Arithmetic.divide_counts
#print axioms ECDSAAdd.Arithmetic.divide_wires
#print axioms ECDSAAdd.Arithmetic.divide_qubits
#print axioms ECDSAAdd.Arithmetic.pointCode_injective
#print axioms ECDSAAdd.Arithmetic.pointInPlaceNegate_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceSquare_correct
#print axioms ECDSAAdd.Arithmetic.pointInPlaceClearSlope_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceGeneric_point
#print axioms ECDSAAdd.Arithmetic.pointInPlaceCorners_effect
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_frame
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_full_spec
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_counts
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_wires
#print axioms ECDSAAdd.Arithmetic.pointInPlaceFinite_qubits
#print axioms ECDSAAdd.montgomery_two_stages
#print axioms ECDSAAdd.Arithmetic.rotateRightBits_spec
#print axioms ECDSAAdd.Arithmetic.rotateLeftBits_spec
#print axioms ECDSAAdd.Arithmetic.montNormalize_correct
#print axioms ECDSAAdd.Arithmetic.montDenormalize_correct
#print axioms ECDSAAdd.Arithmetic.montPrepare_spec
#print axioms ECDSAAdd.Arithmetic.montRestore_spec
#print axioms ECDSAAdd.Arithmetic.constPrepare_spec
#print axioms ECDSAAdd.Arithmetic.constRestore_spec
#print axioms ECDSAAdd.Arithmetic.montP_correct
#print axioms ECDSAAdd.Arithmetic.montQ_correct
#print axioms ECDSAAdd.Arithmetic.montP_spec
#print axioms ECDSAAdd.Arithmetic.montQ_spec
#print axioms ECDSAAdd.Arithmetic.montPQ_counts
#print axioms ECDSAAdd.Arithmetic.montPQ_wires
#print axioms ECDSAAdd.Arithmetic.montPQ_resources
#print axioms ECDSAAdd.Arithmetic.montMulXor_spec
#print axioms ECDSAAdd.Arithmetic.montMulAdd_spec
#print axioms ECDSAAdd.Arithmetic.montMulSub_spec
#print axioms ECDSAAdd.Arithmetic.montMulControlledAdd_spec
#print axioms ECDSAAdd.Arithmetic.montMulControlledSub_spec
#print axioms ECDSAAdd.Arithmetic.montMulXor_frame
#print axioms ECDSAAdd.Arithmetic.montMulAdd_frame
#print axioms ECDSAAdd.Arithmetic.montMulSub_frame
#print axioms ECDSAAdd.Arithmetic.montMulControlledAdd_frame
#print axioms ECDSAAdd.Arithmetic.montMulControlledSub_frame
#print axioms ECDSAAdd.Arithmetic.montAdapter_counts
#print axioms ECDSAAdd.Arithmetic.montControlledAdapter_counts
#print axioms ECDSAAdd.Arithmetic.montAdapter_wires
#print axioms ECDSAAdd.Arithmetic.montControlledAdapter_wires
#print axioms ECDSAAdd.Arithmetic.montAdapter_qubits
#print axioms ECDSAAdd.Arithmetic.montControlledAdapter_qubits
#print axioms ECDSAAdd.Arithmetic.eraseMask_correct
#print axioms ECDSAAdd.Arithmetic.measuredMaskedAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.measuredMaskedSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.measuredMaskedAddInPlace_frame
#print axioms ECDSAAdd.Arithmetic.measuredMaskedSubInPlace_frame
#print axioms ECDSAAdd.Arithmetic.measuredMaskedInPlace_counts
#print axioms ECDSAAdd.Arithmetic.measuredMaskedInPlace_wires
#print axioms ECDSAAdd.Arithmetic.measuredMaskedInPlace_qubits
#print axioms ECDSAAdd.Arithmetic.lookup10_spec
#print axioms ECDSAAdd.Arithmetic.lookup10_counts
#print axioms ECDSAAdd.Arithmetic.lookup10_core_wires
#print axioms ECDSAAdd.Arithmetic.lookup10_frame
#print axioms ECDSAAdd.inverseScaleFactor_bound
#print axioms ECDSAAdd.inverseScaleFactor_relation
#print axioms ECDSAAdd.montgomery_inverseScaleFactor
#print axioms ECDSAAdd.inverseScaleFactor_halving
#print axioms ECDSAAdd.kaliski_scale_count
#print axioms ECDSAAdd.kaliski_montgomery_scale
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.prepare_spec
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.restore_spec
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.prepare_frame
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.restore_frame
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.wires_subset
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.counts
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_widths
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_work
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_live
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaling_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.scaleLive_subset
#print axioms ECDSAAdd.Arithmetic.compactScale_values
#print axioms ECDSAAdd.Arithmetic.InverseScaledMiddle.congr
#print axioms ECDSAAdd.Arithmetic.compactConstants_values
#print axioms ECDSAAdd.Arithmetic.compactNeg_values
#print axioms ECDSAAdd.Arithmetic.compactReady_iff
#print axioms ECDSAAdd.Arithmetic.InverseScaleLayout.work_covered
#print axioms ECDSAAdd.kaliski_terminal_even
#print axioms ECDSAAdd.kaliski_terminal_values
#print axioms ECDSAAdd.negative_even_value
#print axioms ECDSAAdd.negative_even_restore
#print axioms ECDSAAdd.Arithmetic.negativeEven_correct
#print axioms ECDSAAdd.Arithmetic.negativeEven_spec
#print axioms ECDSAAdd.Arithmetic.negativeEven_counts
#print axioms ECDSAAdd.Arithmetic.negativeEven_wires

#print axioms ECDSAAdd.kaliski_swap_from_r
#print axioms ECDSAAdd.Arithmetic.recoverSwap_state
#print axioms ECDSAAdd.Arithmetic.oneBitRound_spec
#print axioms ECDSAAdd.Arithmetic.oneBitUnround_spec
#print axioms ECDSAAdd.Arithmetic.oneBitRound_counts
#print axioms ECDSAAdd.Arithmetic.oneBitRound_wires
#print axioms ECDSAAdd.Arithmetic.oneBitRound_preserves
#print axioms ECDSAAdd.Arithmetic.oneBitRound_qubits
#print axioms ECDSAAdd.Arithmetic.oneBitLoop_correct
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_correct
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_counts
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_wires
#print axioms ECDSAAdd.Arithmetic.oneBitRecordLoop_qubits
#print axioms ECDSAAdd.Arithmetic.OneBitRecordsValues.zero_iff
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactBorrow_length
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.idleBorrow_length
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compact_parts_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compact_inputs_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactCore_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactCore_length
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.idleBorrow_subset
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_widths
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_work
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_live
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactScaling_nodup
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactNeg_widths
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactNeg_partition
#print axioms ECDSAAdd.Arithmetic.InverseLoopLayout.compactNeg_nodup
#print axioms ECDSAAdd.Arithmetic.terminalConstants_correct
#print axioms ECDSAAdd.Arithmetic.terminalConstants_spec
#print axioms ECDSAAdd.Arithmetic.terminalConstants_resources
#print axioms ECDSAAdd.Arithmetic.square_sum128_bound
#print axioms ECDSAAdd.Arithmetic.square_sum128_square_bound
#print axioms ECDSAAdd.Arithmetic.triangularSquare_correct
#print axioms ECDSAAdd.Arithmetic.triangularSquare_spec
#print axioms ECDSAAdd.Arithmetic.triangularSquareClear_spec
#print axioms ECDSAAdd.Arithmetic.triangularSquare_frame
#print axioms ECDSAAdd.Arithmetic.triangularSquareClear_frame
#print axioms ECDSAAdd.Arithmetic.triangularSquare_counts
#print axioms ECDSAAdd.Arithmetic.triangularSquare_wires
#print axioms ECDSAAdd.Arithmetic.SquareReduction.reduced_square_word
#print axioms ECDSAAdd.Arithmetic.squareFold_correct
#print axioms ECDSAAdd.Arithmetic.squareFold_counts
#print axioms ECDSAAdd.Arithmetic.squareFold_wires_subset
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_spec
#print axioms ECDSAAdd.Arithmetic.karatsubaSquareClear_spec
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_frame
#print axioms ECDSAAdd.Arithmetic.karatsubaSquareClear_frame
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_counts
#print axioms ECDSAAdd.Arithmetic.karatsubaSquare_wires_subset
#print axioms ECDSAAdd.Arithmetic.squareReduce_correct
#print axioms ECDSAAdd.Arithmetic.squareReduce_frame
#print axioms ECDSAAdd.Arithmetic.squareReduce_counts
#print axioms ECDSAAdd.Arithmetic.squareReduce_wires_subset
#print axioms ECDSAAdd.Arithmetic.squareSub_spec
#print axioms ECDSAAdd.Arithmetic.squareSub_frame
#print axioms ECDSAAdd.Arithmetic.squareSub_counts
#print axioms ECDSAAdd.Arithmetic.squareSub_wires_subset
#print axioms ECDSAAdd.Arithmetic.SquareSubLayout.work_length
#print axioms ECDSAAdd.Arithmetic.SquareSubLayout.fromPool_work
#print axioms ECDSAAdd.Arithmetic.SquareSubLayout.fromPool_nodup
#print axioms ECDSAAdd.Arithmetic.squareSub_correct
#print axioms ECDSAAdd.Arithmetic.pointInPlaceSquare_correct
#print axioms ECDSAAdd.Arithmetic.eraseSwap_correct
#print axioms ECDSAAdd.Arithmetic.eraseSwap_frame
#print axioms ECDSAAdd.Arithmetic.eraseSwap_counts
#print axioms ECDSAAdd.Arithmetic.eraseSwap_wires
#print axioms ECDSAAdd.Arithmetic.eraseSwap_state
#print axioms ECDSAAdd.Arithmetic.controlledHalf_spec
#print axioms ECDSAAdd.Arithmetic.controlledDouble_spec
#print axioms ECDSAAdd.Arithmetic.controlledHalf_frame
#print axioms ECDSAAdd.Arithmetic.controlledDouble_frame
#print axioms ECDSAAdd.Arithmetic.controlledUnary_counts
#print axioms ECDSAAdd.Arithmetic.controlledUnary_wires
#print axioms ECDSAAdd.Arithmetic.controlledUnary_qubits
#print axioms ECDSAAdd.valueStep_projection
#print axioms ECDSAAdd.valueIter_projection
#print axioms ECDSAAdd.valueIter_terminal
#print axioms ECDSAAdd.value_unstep_step
#print axioms ECDSAAdd.valueReplayStep_add
#print axioms ECDSAAdd.valueReplayStep_smul
#print axioms ECDSAAdd.valueReplayUnstep_step
#print axioms ECDSAAdd.valueReplayStep_unstep
#print axioms ECDSAAdd.valueReplay_add
#print axioms ECDSAAdd.valueReplay_smul
#print axioms ECDSAAdd.valueReplayInverse_replay
#print axioms ECDSAAdd.valueReplay_replayInverse
#print axioms ECDSAAdd.valueReplay_trace
#print axioms ECDSAAdd.valueReplay_terminal
#print axioms ECDSAAdd.dialog_quotient
#print axioms ECDSAAdd.dialog_product
#print axioms ECDSAAdd.Arithmetic.valueRound_spec
#print axioms ECDSAAdd.Arithmetic.valueUnround_spec
#print axioms ECDSAAdd.Arithmetic.valueRound_frame
#print axioms ECDSAAdd.Arithmetic.valueRound_counts
#print axioms ECDSAAdd.Arithmetic.valueRound_wires
#print axioms ECDSAAdd.Arithmetic.valueRound_qubits
#print axioms ECDSAAdd.Arithmetic.valueRound_257_resources
#print axioms ECDSAAdd.Arithmetic.replayCell_spec
#print axioms ECDSAAdd.Arithmetic.replayUncell_spec
#print axioms ECDSAAdd.Arithmetic.replayCell_frame
#print axioms ECDSAAdd.Arithmetic.replayUncell_frame
#print axioms ECDSAAdd.Arithmetic.replayCell_counts
#print axioms ECDSAAdd.Arithmetic.replayCell_wires
#print axioms ECDSAAdd.Arithmetic.replayCell_qubits
#print axioms ECDSAAdd.Arithmetic.replayRound_spec
#print axioms ECDSAAdd.Arithmetic.replayUnround_spec
#print axioms ECDSAAdd.Arithmetic.replayLoop_spec
#print axioms ECDSAAdd.Arithmetic.replayUnloop_spec
#print axioms ECDSAAdd.Arithmetic.replay_padding
#print axioms ECDSAAdd.Arithmetic.replayLoop_counts
#print axioms ECDSAAdd.Arithmetic.replay512_counts
#print axioms ECDSAAdd.Arithmetic.replayLoop_wires
#print axioms ECDSAAdd.Arithmetic.replayLoop_wires_subset
#print axioms ECDSAAdd.Arithmetic.replay512_qubits
#print axioms ECDSAAdd.Arithmetic.replayNatStep_field
#print axioms ECDSAAdd.Arithmetic.replayNatUnstep_field
#print axioms ECDSAAdd.Arithmetic.replayNatLoop_field
#print axioms ECDSAAdd.Arithmetic.replayNatUnloop_field
#print axioms ECDSAAdd.valueStep_count
#print axioms ECDSAAdd.valueIter_k_mono
#print axioms ECDSAAdd.value_active_final
#print axioms ECDSAAdd.Arithmetic.valueLoop_spec
#print axioms ECDSAAdd.Arithmetic.valueUnloop_spec
#print axioms ECDSAAdd.Arithmetic.valueLoop_counts
#print axioms ECDSAAdd.Arithmetic.valueLoop_wires
#print axioms ECDSAAdd.Arithmetic.valueLoop_qubits
#print axioms ECDSAAdd.Arithmetic.replayControls_trace
#print axioms ECDSAAdd.Arithmetic.dialogReplay_division
#print axioms ECDSAAdd.Arithmetic.dialogReplay_multiplication
#print axioms ECDSAAdd.Arithmetic.DialogLayout.replay_valid
#print axioms ECDSAAdd.Arithmetic.dialogLoad_correct
#print axioms ECDSAAdd.Arithmetic.dialogDivide_spec
#print axioms ECDSAAdd.Arithmetic.dialogMultiply_spec
#print axioms ECDSAAdd.Arithmetic.dialog_counts
#print axioms ECDSAAdd.Arithmetic.dialog_wires
#print axioms ECDSAAdd.Arithmetic.dialog_qubits
#print axioms ECDSAAdd.Arithmetic.dialog_resources
#print axioms ECDSAAdd.Arithmetic.dialog_frame
#print axioms ECDSAAdd.Secp256k1.dialog_generic_iff
#print axioms ECDSAAdd.Secp256k1.dialog_denominators_ne_zero
#print axioms ECDSAAdd.Secp256k1.dialog_exception_add
#print axioms ECDSAAdd.Secp256k1.dialog_translated_exception
#print axioms ECDSAAdd.Secp256k1.dialog_input_disjoint
#print axioms ECDSAAdd.Secp256k1.dialog_translated_flags
#print axioms ECDSAAdd.Secp256k1.dialog_output_disjoint
#print axioms ECDSAAdd.Secp256k1.dialogOrdinary_true
#print axioms ECDSAAdd.Secp256k1.dialogFlags_output
#print axioms ECDSAAdd.Secp256k1.dialogCorners_nat
#print axioms ECDSAAdd.Secp256k1.dialogCorners_bool
#print axioms ECDSAAdd.Arithmetic.DialogLayout.fromPool_wires_perm
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.dialogPort_nodup
#print axioms ECDSAAdd.Arithmetic.pointDialogConstantAdd_correct
#print axioms ECDSAAdd.Arithmetic.pointDialogNegate_correct
#print axioms ECDSAAdd.Arithmetic.pointDialog_arithmetic_correct
#print axioms ECDSAAdd.Arithmetic.pointDialogSquare_correct
#print axioms ECDSAAdd.Arithmetic.pointDialogGeneric_true
#print axioms ECDSAAdd.Arithmetic.pointDialogGeneric_false
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_spec
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_full_spec
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_frame
#print axioms ECDSAAdd.Arithmetic.pointDialogGeneric_counts
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_counts
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_wires
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_qubits
#print axioms ECDSAAdd.Arithmetic.replayNatUnstep_step
#print axioms ECDSAAdd.Arithmetic.replayNatStep_unstep
#print axioms ECDSAAdd.Arithmetic.replayNatUnloop_loop
#print axioms ECDSAAdd.Arithmetic.replayNatLoop_unloop
#print axioms ECDSAAdd.Arithmetic.replayCell_roundTrip_spec
#print axioms ECDSAAdd.Arithmetic.replayUncell_roundTrip_spec
#print axioms ECDSAAdd.Arithmetic.replayLoop_roundTrip_spec
#print axioms ECDSAAdd.Arithmetic.replayUnloop_roundTrip_spec
#print axioms ECDSAAdd.Arithmetic.measuredShortAddInPlace_spec
#print axioms ECDSAAdd.Arithmetic.measuredShortSubInPlace_spec
#print axioms ECDSAAdd.Arithmetic.measuredShortInPlace_counts
#print axioms ECDSAAdd.Arithmetic.measuredShortAddInPlace_frame
#print axioms ECDSAAdd.Arithmetic.measuredShortSubInPlace_frame
#print axioms ECDSAAdd.Arithmetic.measuredShortInPlace_wires
#print axioms ECDSAAdd.Arithmetic.triangularSquareCount_twice
#print axioms ECDSAAdd.Arithmetic.triangularSquareCount_closed
#print axioms ECDSAAdd.Arithmetic.skywalkArithmetic_spec
#print axioms ECDSAAdd.Arithmetic.skywalkArithmetic_frame
#print axioms ECDSAAdd.Arithmetic.skywalkArithmetic_counts
#print axioms ECDSAAdd.Arithmetic.skywalkArithmetic_support
#print axioms ECDSAAdd.Arithmetic.pointSkywalkArithmetic_correct
#print axioms ECDSAAdd.Arithmetic.pointSkywalkArithmetic_counts
#print axioms ECDSAAdd.Arithmetic.pointSkywalkArithmetic_support
#print axioms ECDSAAdd.SkywalkNat.coprime_sum_le_product_succ
#print axioms ECDSAAdd.SkywalkNat.iter_sum_product_width
#print axioms ECDSAAdd.SkywalkNat.iter_sum_initial_width
#print axioms ECDSAAdd.SkywalkRails.encode_abs_sum_bound
#print axioms ECDSAAdd.SkywalkRails.route_half_width
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.views
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.short_nodup
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.high_nodup
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.q_high
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.high_away_short
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.rest_away_short
#print axioms ECDSAAdd.Arithmetic.NarrowSignedRecordLayout.other_away_high
#print axioms ECDSAAdd.Arithmetic.narrow_fanout_correct
#print axioms ECDSAAdd.Arithmetic.narrow_fanout_twice
#print axioms ECDSAAdd.Arithmetic.narrow_signed_append
#print axioms ECDSAAdd.Arithmetic.narrow_signed_prefix
#print axioms ECDSAAdd.Arithmetic.narrow_signed_extend
#print axioms ECDSAAdd.Arithmetic.narrowSignedRecord_spec
#print axioms ECDSAAdd.Arithmetic.narrowSignedUnrecord_spec
#print axioms ECDSAAdd.Arithmetic.narrowSignedRecord_counts
#print axioms ECDSAAdd.Arithmetic.narrowSignedRecord_support
#print axioms ECDSAAdd.Arithmetic.narrowSignedRecord_frame
#print axioms ECDSAAdd.Arithmetic.narrowSignedRecord_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSignedRecord_full_frame
#print axioms ECDSAAdd.Arithmetic.narrowSignedUnrecord_full_frame
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRecord_views
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRecord_widths
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRecord_nodup
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRecord_eq
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkTick_eq
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkTick_spec
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkTick_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkTick_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkTick_wires_subset
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkWidth_bounds
#print axioms ECDSAAdd.Arithmetic.narrowSkywalk_iter_fit
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkStage_step
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkLoop_spec
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkLoop_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkLoop_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkLoop_support
#print axioms ECDSAAdd.Arithmetic.skywalkSignDelta_correct
#print axioms ECDSAAdd.Arithmetic.skywalkSignDeltaErase_correct
#print axioms ECDSAAdd.Arithmetic.skywalkSignDelta_counts
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.lengths
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.full_nodup
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.low_nodup
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.bank_nodup
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.delta_bank
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.distinct
#print axioms ECDSAAdd.Arithmetic.NarrowSkywalkSwapLayout.outside_low
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkSwap_correct
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkSwap_eq
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkSwap_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_eq
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkSwap_support
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_support
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_views
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_delta_mem
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_valid
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_copies
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRouteWidth_bounds
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_iter_fit
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedTick_eq
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkSwap_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoute_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedTick_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedTick_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedTick_support
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedStage_step
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkScheduledTick_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedLoop_spec
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedLoop_roundtrip
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkScheduledTick_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedLoop_counts
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkScheduledTick_support
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedLoop_support
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRoutedUnloop_restore_pool
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRouted512_spec
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRouted512_tape
#print axioms ECDSAAdd.Arithmetic.narrowSkywalkRouted512_counts
#print axioms ECDSAAdd.Arithmetic.fusedHalfParityClear_correct
#print axioms ECDSAAdd.Arithmetic.fusedHalfParityClear_counts
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionFlagsSeed_correct
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionFlagsErase_correct
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionFlags_counts
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionWordValue_selector
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionWordLoad_correct
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionWordLoad_counts
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionApply_correct
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionApply_counts
#print axioms ECDSAAdd.Arithmetic.fusedRawReduction
#print axioms ECDSAAdd.Arithmetic.fusedRawNormalize_correct
#print axioms ECDSAAdd.Arithmetic.fusedRawNormalize_shared_correct
#print axioms ECDSAAdd.Arithmetic.fusedRawNormalize_counts
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionWordValue_integer
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionMachine
#print axioms ECDSAAdd.Arithmetic.fusedThresholdFlagsSeed_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdFlagsErase_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdFlags_counts
#print axioms ECDSAAdd.Arithmetic.fusedThresholdWordValue_integer
#print axioms ECDSAAdd.Arithmetic.fusedThresholdWordLoad_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdWordLoad_counts
#print axioms ECDSAAdd.Arithmetic.fusedThresholdRecover_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdRecover_shared_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdRecover_counts
#print axioms ECDSAAdd.Arithmetic.fusedThresholdMachine
#print axioms ECDSAAdd.Arithmetic.fusedEvenHalf_correct
#print axioms ECDSAAdd.Arithmetic.fusedEvenHalf_counts
#print axioms ECDSAAdd.Arithmetic.fusedFlagsMove_correct
#print axioms ECDSAAdd.Arithmetic.fusedFlagsMove_counts
#print axioms ECDSAAdd.Arithmetic.fusedWordLowBit
#print axioms ECDSAAdd.Arithmetic.fusedWordTopBit
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfCandidate_counts
#print axioms ECDSAAdd.Arithmetic.fusedRawParity
#print axioms ECDSAAdd.Arithmetic.fusedRawSign
#print axioms ECDSAAdd.Arithmetic.fusedThresholdRecover_clears
#print axioms ECDSAAdd.Arithmetic.fusedThresholdRecover_shared_clears
#print axioms ECDSAAdd.Arithmetic.fusedHalfParityClear_from_result
#print axioms ECDSAAdd.Arithmetic.fusedCanonicalGuards
#print axioms ECDSAAdd.Arithmetic.fusedSourceHalfValue
#print axioms ECDSAAdd.Arithmetic.fusedThresholdPrepare_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdUnprepare_correct
#print axioms ECDSAAdd.Arithmetic.fusedThresholdPreparation_counts
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfFront_correct
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfFront_counts
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfBack_correct
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfBack_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.widths
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.front_nodup
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.move_nodup
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.back_nodup
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.program_eq_stages
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedIds_nodup
#print axioms ECDSAAdd.Arithmetic.fusedSharedIds_bound
#print axioms ECDSAAdd.Arithmetic.fusedSharedSites_nodup
#print axioms ECDSAAdd.Arithmetic.fusedSharedSites_subset
#print axioms ECDSAAdd.Arithmetic.fusedSharedSites_record_outside
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_widths
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_targetLow
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_source
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_wires
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_nodup
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_early
#print axioms ECDSAAdd.Arithmetic.fusedSharedSignedHalf_counts
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_views
#print axioms ECDSAAdd.Arithmetic.fusedSharedPorts_input
#print axioms ECDSAAdd.Arithmetic.fusedSharedKernel_correct
#print axioms ECDSAAdd.Arithmetic.fusedFieldSignedHalf_counts
#print axioms ECDSAAdd.Arithmetic.fusedField_result
#print axioms ECDSAAdd.Arithmetic.fusedFieldSignedHalf_correct
#print axioms ECDSAAdd.Arithmetic.retainedAdd_counts
#print axioms ECDSAAdd.Arithmetic.retainedAdd_support
#print axioms ECDSAAdd.Arithmetic.retainedAdd_roundtrip
#print axioms ECDSAAdd.Arithmetic.retainedAdd_finish_image
#print axioms ECDSAAdd.Arithmetic.retainedAddStart_correct
#print axioms ECDSAAdd.Arithmetic.retainedAdd_start_image
#print axioms ECDSAAdd.Arithmetic.retainedAdd_image_congr
#print axioms ECDSAAdd.Arithmetic.fusedRetainedThresholdCore_counts
#print axioms ECDSAAdd.Arithmetic.fusedRetainedThresholdRecover_counts
#print axioms ECDSAAdd.Arithmetic.fusedRetainedThresholdCore_correct
#print axioms ECDSAAdd.Arithmetic.fusedRetainedThresholdRecover_correct
#print axioms ECDSAAdd.Arithmetic.fusedRetainedThresholdRecover_eq_reference
#print axioms ECDSAAdd.Arithmetic.replace_zero_measurement_prefix
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfRetainedBack_correct
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfRetainedBack_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.retained_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.retained_correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedKernel_counts
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedKernel_correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedSignedHalf_counts
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedSignedHalf_correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedCell_spec
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedCell_frame
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedCell_counts
#print axioms ECDSAAdd.Arithmetic.fusedShared_work_clean
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetained_leaf_frame
#print axioms ECDSAAdd.Arithmetic.skywalkShared_fused_tape_layout
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedReplay_spec
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedReplay_counts
#print axioms ECDSAAdd.Arithmetic.skywalkFieldDivisionRetained_spec
#print axioms ECDSAAdd.Arithmetic.skywalkFieldDivisionRetained_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.retained_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedKernel_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedSignedHalf_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedCell_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedRetainedReplay_support
#print axioms ECDSAAdd.Arithmetic.skywalkFieldDivisionRetained_support
#print axioms ECDSAAdd.FusedSignedHalf.inverseValue_bound
#print axioms ECDSAAdd.FusedSignedHalf.inverseValue_field
#print axioms ECDSAAdd.FusedSignedHalf.result_inverseValue
#print axioms ECDSAAdd.FusedSignedHalf.inverseValue_result
#print axioms ECDSAAdd.Arithmetic.fusedHalfParityToggle_correct
#print axioms ECDSAAdd.Arithmetic.fusedHalfParitySeed_correct
#print axioms ECDSAAdd.Arithmetic.fusedRetainedFlagToggle_correct
#print axioms ECDSAAdd.Arithmetic.fusedRetainedFlagToggle_counts
#print axioms ECDSAAdd.Arithmetic.fusedInverseFlagSeed_counts
#print axioms ECDSAAdd.Arithmetic.fusedInverseFlagSeed_correct
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionUndo_correct
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionUndo_counts
#print axioms ECDSAAdd.Arithmetic.fusedInverseCorrection_bound
#print axioms ECDSAAdd.Arithmetic.fusedCorrectionUndoMachine
#print axioms ECDSAAdd.Arithmetic.fusedSignedWordInverse
#print axioms ECDSAAdd.Arithmetic.fusedInverseCorrectionFlagsSeed_counts
#print axioms ECDSAAdd.Arithmetic.fusedInverseCorrectionFlagsSeed_correct
#print axioms ECDSAAdd.Arithmetic.fusedInverseRawFlagClear_correct
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfUnfront_counts
#print axioms ECDSAAdd.Arithmetic.fusedSignedHalfUnfront_correct
#print axioms ECDSAAdd.Arithmetic.fusedInverseFlagsMove_counts
#print axioms ECDSAAdd.Arithmetic.fusedInverseFlagsMove_correct
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.inverse_counts
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseKernel_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.inverse_correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseKernel_correct
#print axioms ECDSAAdd.Arithmetic.fusedFieldInverse_result
#print axioms ECDSAAdd.Arithmetic.fusedFieldInverse_correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseSigned_counts
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseSigned_correct
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverse_leaf_frame
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseCell_counts
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseReplay_spec
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseReplay_counts
#print axioms ECDSAAdd.Arithmetic.skywalkFieldMultiplicationRetained_spec
#print axioms ECDSAAdd.Arithmetic.skywalkFieldMultiplicationRetained_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.inverse_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseKernel_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseSigned_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseCell_support
#print axioms ECDSAAdd.Arithmetic.fusedSharedInverseReplay_support
#print axioms ECDSAAdd.Arithmetic.skywalkFieldMultiplicationRetained_support
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.listed_subset
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.early_mem
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.constant_mem
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.sourceHalf_mem
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.correctionWordLoad_constant_support
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.correctionFlagsErase_support
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.move_support
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.retainedBack_support
#print axioms ECDSAAdd.Arithmetic.retained_field_subset_shared
#print axioms ECDSAAdd.Arithmetic.retained_tape_subset_shared
#print axioms ECDSAAdd.Arithmetic.retained_copy_frame
#print axioms ECDSAAdd.Arithmetic.compactSignedHalfFront_correct
#print axioms ECDSAAdd.Arithmetic.compactSignedHalfFront_counts
#print axioms ECDSAAdd.Arithmetic.compactSignedHalfUnfront_correct
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_widths
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_forward_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_inverse_counts
#print axioms ECDSAAdd.Arithmetic.compactShared_forward_counts
#print axioms ECDSAAdd.Arithmetic.compactShared_inverse_counts
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compactSource_sublist
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compactTarget_sublist
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compactConstant_sublist
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compactCarry_sublist
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_front_nodup
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_source_value
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_target_value
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_constant_clean
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_carry_clean
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_target_lift
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compactForward_correct
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compactInverse_correct
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_forward_support
#print axioms ECDSAAdd.Arithmetic.FusedHalfPorts.compact_inverse_support
#print axioms ECDSAAdd.Arithmetic.exactFold_reduction_flag
#print axioms ECDSAAdd.Arithmetic.exactFold_low_and_top
#print axioms ECDSAAdd.Arithmetic.exactFold_recover_flag
#print axioms ECDSAAdd.Arithmetic.exactFold_reflection
#print axioms ECDSAAdd.Arithmetic.exactFold_mask_square
#print axioms ECDSAAdd.Arithmetic.exactFold_square_mod8
#print axioms ECDSAAdd.Arithmetic.exactFold_leaf128_canonical
#print axioms ECDSAAdd.Arithmetic.exactFold_rotate128_canonical
#print axioms ECDSAAdd.Arithmetic.canonical_flag_bool
#print axioms ECDSAAdd.Arithmetic.canonical_corrected_extended
#print axioms ECDSAAdd.Arithmetic.canonical_corrected_bound
#print axioms ECDSAAdd.Arithmetic.borrowMajority_correct
#print axioms ECDSAAdd.Arithmetic.eraseBorrow_correct
#print axioms ECDSAAdd.Arithmetic.borrowMajority_counts
#print axioms ECDSAAdd.Arithmetic.eraseBorrow_counts
#print axioms ECDSAAdd.Arithmetic.eraseLtChain_counts
#print axioms ECDSAAdd.Arithmetic.borrow_threshold
#print axioms ECDSAAdd.Arithmetic.eraseLtChain_correct
#print axioms ECDSAAdd.Arithmetic.mappedMajority_correct
#print axioms ECDSAAdd.Arithmetic.mappedEraseCarry_correct
#print axioms ECDSAAdd.Arithmetic.mappedSum_correct
#print axioms ECDSAAdd.Arithmetic.mappedValue_congr
#print axioms ECDSAAdd.Arithmetic.mappedBit_counts
#print axioms ECDSAAdd.Arithmetic.mappedBit_value_congr
#print axioms ECDSAAdd.Arithmetic.mappedAdd_correct
#print axioms ECDSAAdd.Arithmetic.mappedAdd_counts
#print axioms ECDSAAdd.Arithmetic.mappedBit_wires
#print axioms ECDSAAdd.Arithmetic.mappedAdd_wires_subset
#print axioms ECDSAAdd.Arithmetic.mappedConstantBit_value
#print axioms ECDSAAdd.Arithmetic.mappedConstant_length
#print axioms ECDSAAdd.Arithmetic.mappedConstant_value
#print axioms ECDSAAdd.Arithmetic.mappedConstant_wires
#print axioms ECDSAAdd.Arithmetic.mappedRead_value
#print axioms ECDSAAdd.Arithmetic.mappedRead_complement
#print axioms ECDSAAdd.Arithmetic.mappedRead_wires
#print axioms ECDSAAdd.Arithmetic.mappedValue_append
#print axioms ECDSAAdd.Arithmetic.mappedDiagonal_length
#print axioms ECDSAAdd.Arithmetic.mappedRead_length
#print axioms ECDSAAdd.Arithmetic.mappedDiagonal_value
#print axioms ECDSAAdd.Arithmetic.mappedConstAdd_counts
#print axioms ECDSAAdd.Arithmetic.mappedConstAdd_correct
#print axioms ECDSAAdd.Arithmetic.carryBit_swap
#print axioms ECDSAAdd.Arithmetic.constantBorrow_correct
#print axioms ECDSAAdd.Arithmetic.constantBorrowErase_correct
#print axioms ECDSAAdd.Arithmetic.constantBorrow_counts
#print axioms ECDSAAdd.Arithmetic.compareConstantLt_counts
#print axioms ECDSAAdd.Arithmetic.compareConstantGe_counts
#print axioms ECDSAAdd.Arithmetic.compareConstantLt_correct
#print axioms ECDSAAdd.Arithmetic.compareConstantGe_correct
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.program_counts
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.secp_program_counts
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.protected_away
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.flags_away
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.Frame.source
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.Frame.clean
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.extended_value
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.extended_decode
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.Frame.afterExtended
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.sum_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.ge_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.cx_flag_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.cx_high_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.correction_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.erase_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.program_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.program_correct
#print axioms ECDSAAdd.Arithmetic.mappedValue_lt
#print axioms ECDSAAdd.Arithmetic.mappedSub_correct
#print axioms ECDSAAdd.Arithmetic.mappedSub_counts
#print axioms ECDSAAdd.Arithmetic.mappedDiagonal_wires
#print axioms ECDSAAdd.Arithmetic.mappedDiagonal_exact
#print axioms ECDSAAdd.Arithmetic.mappedDiagSub_correct
#print axioms ECDSAAdd.Arithmetic.mappedDiagAdd_correct
#print axioms ECDSAAdd.Arithmetic.mappedDiag_counts
#print axioms ECDSAAdd.Arithmetic.mappedDiag_roundtrip
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquare_counts
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquare_correct
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquare_counts_128
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquare_counts_129
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquare_roundtrip
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquareClear_correct
#print axioms ECDSAAdd.Arithmetic.maskedSquareAction_correct
#print axioms ECDSAAdd.Arithmetic.copyNone_free
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_bank_widths
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredCore_widths
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_small_operation_counts
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_counts
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFolds_counts
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_item_prices
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.withMeasuredSquare_counts
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredProgram_counts
#print axioms ECDSAAdd.Arithmetic.mappedSub_wires_subset
#print axioms ECDSAAdd.Arithmetic.mappedConstAdd_wires_subset
#print axioms ECDSAAdd.Arithmetic.constantBorrow_wires_subset
#print axioms ECDSAAdd.Arithmetic.compareConstantLt_wires_subset
#print axioms ECDSAAdd.Arithmetic.compareConstantGe_wires_subset
#print axioms ECDSAAdd.Arithmetic.borrowPair_wires_subset
#print axioms ECDSAAdd.Arithmetic.eraseLtChain_wires_subset
#print axioms ECDSAAdd.Arithmetic.mappedSignedSquare_wires_subset
#print axioms ECDSAAdd.Arithmetic.copyRegister_wires_subset
#print axioms ECDSAAdd.Arithmetic.MeasuredCanonicalModLayout.program_wires_subset
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_small_support
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_support
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFolds_support
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.withMeasuredSquare_support
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_items_support
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredProgram_support
#print axioms ECDSAAdd.Arithmetic.pointMeasuredSquareCandidate_counts
#print axioms ECDSAAdd.Arithmetic.pointMeasuredSquareCandidate_support
#print axioms ECDSAAdd.Arithmetic.pointMeasuredSquareCandidate_stage_support
#print axioms ECDSAAdd.Arithmetic.pointMeasuredSquareCandidate_stage_sites
#print axioms ECDSAAdd.Arithmetic.pointMeasuredSquareCandidate_correct
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.canonical_and_restore
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.protected_away
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.flag_away
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.Frame.clean
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.ge_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.add_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.normalize_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.restore_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.not_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.literal_add_frame
#print axioms ECDSAAdd.Arithmetic.MeasuredSourceNormalizeLayout.reflect_frame
#print axioms ECDSAAdd.Arithmetic.measuredFoldKernel_correct
#print axioms ECDSAAdd.Arithmetic.copySlice_zero_correct
#print axioms ECDSAAdd.Arithmetic.measuredCopiedFold_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_eq_copied
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_interfaces
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_carry_clean
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.reflectOutput_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFoldsValue_lt
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.squareFrame_clean
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFold_frame
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredReflection_frame
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFolds_frame
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredReflection_zmod
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredFoldsValue_cast
#print axioms ECDSAAdd.Arithmetic.maskedSquareCallback_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_leaf_bank_count
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_leaf_nodup
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_leaf_banks_clean
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.withMeasuredSquare_eq_callback
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.withMeasuredSquare_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_short_canonical
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_short_view
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_naf_views
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_rotated_count
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_rotated_square_view
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_leaf128_view
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_shifted_product_views
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredA_views
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredB_views
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredC_views
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredSignedSum_append
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_naf_sum
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_positive_rotate_sum
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_shifted_sum
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredA_sum
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredB_sum
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredC_sum
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_concrete_orientations
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_controlled_square_identity
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_results_lt
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredAResult_cast
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredBResult_cast
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredCMiddleResult_cast
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredOrientationCast_injective
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_product_frame_clean
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.withMeasuredSquare_contribution
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_partial_product_value
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredBranchA_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredBranchB_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredBranchC_middle_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_sum_count
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_sum_aux_away
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_sum_disjoint
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredBranchC_correct
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredCompleteResult_lt
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredCompleteResult_exact
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measured_input_out_disjoint
#print axioms ECDSAAdd.Arithmetic.CuccaroStreamedSquareWideLayout.measuredProgram_correct
#print axioms ECDSAAdd.Arithmetic.compactNegateValue_exact
#print axioms ECDSAAdd.Arithmetic.compactNegateValue_zero
#print axioms ECDSAAdd.Arithmetic.xorConstant_ones
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.known_away
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.zero_away
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.Frame.clean
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.checkZero_frame
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.complement_frame
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.add_frame
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.program_frame
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.program_correct
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.program_counts
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.program_support
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.reflection_frame
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.reflection_correct
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.reflection_counts
#print axioms ECDSAAdd.Arithmetic.CompactRecoveryNegateLayout.reflection_support
#print axioms ECDSAAdd.Arithmetic.compactRecoveryConstant_correct
#print axioms ECDSAAdd.Arithmetic.compactRecoveryConstant_counts
#print axioms ECDSAAdd.Arithmetic.compactRecoveryConstant_support
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.recoveryConstant_widths
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.recoveryConstant_pool
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.recoveryConstant_nodup
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.recoveryNegate_pool
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.recoveryNegate_nodup
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.recoveryStageSites_certified
#print axioms ECDSAAdd.Arithmetic.pointRecoveryConstantAdd_correct
#print axioms ECDSAAdd.Arithmetic.pointRecoveryNegate_correct
#print axioms ECDSAAdd.Arithmetic.pointRecoveryReflection_correct
#print axioms ECDSAAdd.Arithmetic.pointRecoveryConstantAdd_counts
#print axioms ECDSAAdd.Arithmetic.pointRecoveryNegate_counts
#print axioms ECDSAAdd.Arithmetic.pointRecoveryConstantAdd_support
#print axioms ECDSAAdd.Arithmetic.pointRecoveryNegate_support
#print axioms ECDSAAdd.Arithmetic.pointRecoveryReflection_counts
#print axioms ECDSAAdd.Arithmetic.pointRecoveryReflection_support
#print axioms ECDSAAdd.Arithmetic.pointRecoveryReflection_step
#print axioms ECDSAAdd.Arithmetic.pointRecoveryStage_correct
#print axioms ECDSAAdd.Arithmetic.pointRecoveryStage_counts
#print axioms ECDSAAdd.Arithmetic.pointRecoveryStage_support
#print axioms ECDSAAdd.Arithmetic.pointRecoveryStage_resource_targets
#print axioms ECDSAAdd.Arithmetic.correct_phaseShift
#print axioms ECDSAAdd.Arithmetic.measure_phaseShift
#print axioms ECDSAAdd.Arithmetic.run_phaseShift
#print axioms ECDSAAdd.Arithmetic.run_basis_records
#print axioms ECDSAAdd.Arithmetic.run_local_increment
#print axioms ECDSAAdd.Arithmetic.run_disjoint_commute
#print axioms ECDSAAdd.Arithmetic.compressedHistoryId_region
#print axioms ECDSAAdd.Arithmetic.compressedHistoryId_bound
#print axioms ECDSAAdd.Arithmetic.compressedHistoryMap_injective
#print axioms ECDSAAdd.Arithmetic.compressedHistoryMap_above
#print axioms ECDSAAdd.Arithmetic.skywalkRecordedSymbol_legal
#print axioms ECDSAAdd.Arithmetic.compressedHistoryStage_legal
#print axioms ECDSAAdd.Arithmetic.compressedHistoryEncode_correct
#print axioms ECDSAAdd.Arithmetic.compressedHistory_counts
#print axioms ECDSAAdd.Arithmetic.compressedPackAfter_counts
#print axioms ECDSAAdd.Arithmetic.compressedSkywalkLoop_counts
#print axioms ECDSAAdd.Arithmetic.compressedSkywalk512_counts
#print axioms ECDSAAdd.Arithmetic.compressedHistory_gate_mem
#print axioms ECDSAAdd.Arithmetic.compressedHistory_disjoint_later
#print axioms ECDSAAdd.Arithmetic.compressedHistory_commute_later
#print axioms ECDSAAdd.Arithmetic.compressedPackDue_true
#print axioms ECDSAAdd.Arithmetic.compressedPrefix_disjoint_tick
#print axioms ECDSAAdd.Arithmetic.compressedHistory_windows_disjoint
#print axioms ECDSAAdd.Arithmetic.compressedPrefix_disjoint_next
#print axioms ECDSAAdd.Arithmetic.compressedHistory_site_mem
#print axioms ECDSAAdd.Arithmetic.compressedPrefix_raw_next
#print axioms ECDSAAdd.Arithmetic.compressedIntegerStage_zero
#print axioms ECDSAAdd.Arithmetic.compressedIntegerStage_step
#print axioms ECDSAAdd.Arithmetic.compressedSkywalkLoop_spec
#print axioms ECDSAAdd.Arithmetic.compressedDecodePrefix_measurements
#print axioms ECDSAAdd.Arithmetic.compressedDecodePrefix_inverse
#print axioms ECDSAAdd.Arithmetic.compressedDecodeRange_measurements
#print axioms ECDSAAdd.Arithmetic.compressedDecodeBefore_disjoint_unloop
#print axioms ECDSAAdd.Arithmetic.compressedSkywalkUnloop_normalize
#print axioms ECDSAAdd.Arithmetic.compressedDecodeRange_last
#print axioms ECDSAAdd.Arithmetic.compressedDecodeRange_zero
#print axioms ECDSAAdd.Arithmetic.run_no_measurement_phase
#print axioms ECDSAAdd.Arithmetic.compressedIntegerStage_decoded
#print axioms ECDSAAdd.Arithmetic.compressedSkywalkUnloop_restore_pool
#print axioms ECDSAAdd.Arithmetic.transcriptSelect_value
#print axioms ECDSAAdd.Arithmetic.transcriptSelectCompute_correct
#print axioms ECDSAAdd.Arithmetic.transcriptSelectErase_correct
#print axioms ECDSAAdd.Arithmetic.transcriptSelect_counts
#print axioms ECDSAAdd.Arithmetic.transcriptSelect_finish_correct
#print axioms ECDSAAdd.Arithmetic.transcriptSelectWindow_counts
#print axioms ECDSAAdd.Arithmetic.directZeroDivisorEnter_correct
#print axioms ECDSAAdd.Arithmetic.directZeroDivisorLeave_correct
#print axioms ECDSAAdd.Arithmetic.directDivisor_ne_zero
#print axioms ECDSAAdd.Arithmetic.directDivisor_lt
#print axioms ECDSAAdd.Arithmetic.directZeroDivisorLeave_restores_word
#print axioms ECDSAAdd.Arithmetic.directZeroDivisor_roundtrip
#print axioms ECDSAAdd.Arithmetic.directZeroDivisor_counts
#print axioms ECDSAAdd.Arithmetic.directZeroDivisor_counts_256
#print axioms ECDSAAdd.Arithmetic.directZeroDivisor_wires
#print axioms ECDSAAdd.Arithmetic.directZeroDivisor_qubitCount
#print axioms ECDSAAdd.Arithmetic.directZeroControlled_states
#print axioms ECDSAAdd.Arithmetic.directZeroControlled_counts
#print axioms ECDSAAdd.Arithmetic.transcriptSelectWindow_pairFrame
#print axioms ECDSAAdd.Arithmetic.MixedTranscriptFieldLayout.selection_g
#print axioms ECDSAAdd.Arithmetic.MixedTranscriptFieldLayout.selection_s
#print axioms ECDSAAdd.Arithmetic.MixedTranscriptFieldLayout.cell
#print axioms ECDSAAdd.Arithmetic.MixedTranscriptFieldLayout.outside
#print axioms ECDSAAdd.Arithmetic.MixedTranscriptFieldLayout.pair_outside
#print axioms ECDSAAdd.Arithmetic.MixedTranscriptFieldLayout.eff_ne
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldWindow_frame
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldCell_frame
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptInverseFieldCell_frame
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldCell_counts
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptInverseFieldCell_counts
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptTape_layout
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptReplay_spec
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptInverseReplay_spec
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptReplay_counts
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptInverseReplay_counts
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptUnitTrace_length
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptTape_length
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptControls_zip
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptTape_controls
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptTape_quotient
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptTape_product
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldDivision_spec
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldDivision_counts
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldMultiplication_spec
#print axioms ECDSAAdd.Arithmetic.mixedTranscriptFieldMultiplication_counts
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.skywalkDirectDeclaredSites_length
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.skywalkDirectDeclaredSites_nodup
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.skywalkDirectMap_nodup
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.skywalkDirectMap_coordinates
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.skywalkDirectScalar_nodup
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.skywalkDirectMixed_layout
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_coprime
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_modulus_bound
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_mem
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_block_away
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_input_bit
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_input_zero
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_seed_outside
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_seed_input
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_seed_stage0
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_trace_map
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_tape
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_terminal
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_signed_read_nat
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_terminal_words
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_clear_nodup
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_clear_gates
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_clear_words
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_field_frame
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_pool_away_z
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_loop_outside
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_record_outside
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_unrecord_outside
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_clear_outside
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_stage_congr
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_clear_transport
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_z_input
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_preparation_frame
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_clean_preparation
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_tape_clear
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_seed_components
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_seed_away
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_block_subset_shared
#print axioms ECDSAAdd.Arithmetic.DirectSkywalk.arith_seed_subset_shared
#print axioms ECDSAAdd.Arithmetic.directSkywalkArithmetic_states
#print axioms ECDSAAdd.Arithmetic.directSkywalkArithmetic_run
#print axioms ECDSAAdd.Arithmetic.directSkywalkArithmetic_counts
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_correct
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_counts
#print axioms ECDSAAdd.Arithmetic.DirectSupport.externalKernel
#print axioms ECDSAAdd.Arithmetic.DirectSupport.externalSigned
#print axioms ECDSAAdd.Arithmetic.DirectSupport.externalCells
#print axioms ECDSAAdd.Arithmetic.DirectSupport.selectWindow
#print axioms ECDSAAdd.Arithmetic.DirectSupport.mixedCells
#print axioms ECDSAAdd.Arithmetic.DirectSupport.mixedReplay
#print axioms ECDSAAdd.Arithmetic.DirectSupport.tapeSupport
#print axioms ECDSAAdd.Arithmetic.DirectSupport.unary
#print axioms ECDSAAdd.Arithmetic.DirectSupport.copy
#print axioms ECDSAAdd.Arithmetic.DirectSupport.endpoints
#print axioms ECDSAAdd.Arithmetic.DirectSupport.kernel
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_support
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_declared_support
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_resource_certificate
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.work
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.scalarND
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.seedND
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.rawTargetND
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.allND
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.foldND
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.flagAway
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.signed_extension
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.word_encoding
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.word_sign
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.raw_parity
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.word_parity
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.seedViews_run
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.prepareFold_run
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.releaseSelectors_run
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.fold_correct
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.rotate_folded
#print axioms ECDSAAdd.Arithmetic.BalancedFold.modulusWord
#print axioms ECDSAAdd.Arithmetic.BalancedFold.virtualSource
#print axioms ECDSAAdd.Arithmetic.BalancedFold.selectedSource
#print axioms ECDSAAdd.Arithmetic.BalancedFold.virtualSource_value
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldBits_value
#print axioms ECDSAAdd.Arithmetic.BalancedFold.encode_shift
#print axioms ECDSAAdd.Arithmetic.BalancedFold.minusController
#print axioms ECDSAAdd.Arithmetic.BalancedFold.plusController
#print axioms ECDSAAdd.Arithmetic.BalancedFold.controllers_exclusive
#print axioms ECDSAAdd.Arithmetic.BalancedFold.toggledWord
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldedSum
#print axioms ECDSAAdd.Arithmetic.BalancedFold.raw_sign
#print axioms ECDSAAdd.Arithmetic.BalancedFold.toggled_parity
#print axioms ECDSAAdd.Arithmetic.BalancedFold.cleared_low_word
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldedSum_value
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldedSum_low
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldedSum_cout
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldedSum_bound
#print axioms ECDSAAdd.Arithmetic.BalancedFold.foldBits_sources
#print axioms ECDSAAdd.Arithmetic.BalancedFold.toggle_top_value
#print axioms ECDSAAdd.Arithmetic.BalancedFold.toggledWord_bound
#print axioms ECDSAAdd.Arithmetic.BalancedFold.parity_clear_value
#print axioms ECDSAAdd.Arithmetic.BalancedFold.prepared_upper_bound
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.recoverParity
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.recoverSelectors
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.undoFold
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.undoPreparation
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.rawSubtract
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.program
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.counts
#print axioms ECDSAAdd.Arithmetic.BalancedCleanupXor.xor_states
#print axioms ECDSAAdd.Arithmetic.BalancedCleanupXor.xor_correct
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.recoverParity_correct
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.seed_data_frame
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.seed_signed
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.seed_parity
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.seed_raw_signed
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.support
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.qubitBound
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.foldSources
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.complement_sandwich
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.mappedSub_any_correct
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.subInPlace_any_correct
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.result
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.result_bounds
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.result_half
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.core_correct
#print axioms ECDSAAdd.Arithmetic.BalancedCircuit.program_correct
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.recoverSelectors_run
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.undoPreparation_run
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.result_parity
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.result_sign
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.rotate_unfold
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.undoFold_correct
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.rawSubtract_modular
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.rawSubtract_signed
#print axioms ECDSAAdd.Arithmetic.BalancedConvert.counts
#print axioms ECDSAAdd.Arithmetic.BalancedConvert.predicate_run
#print axioms ECDSAAdd.Arithmetic.BalancedConvert.center_correct
#print axioms ECDSAAdd.Arithmetic.BalancedConvert.canonical_correct
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.prepared_one
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.undoPreparation_word
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.unseed_run
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.unseed_correlations
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.program_correct
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptHalf_frame
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptBody_frame
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptCell_frame
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptReplay_frame
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptCanonicalReplay_frame
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptCanonicalReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptTapeReplay_quotient
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptTapeReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedSharedPorts_clean
#print axioms ECDSAAdd.Arithmetic.balancedPair_narrow
#print axioms ECDSAAdd.Arithmetic.balancedPair_widen
#print axioms ECDSAAdd.Arithmetic.balancedSharedCanonicalReplay_frame
#print axioms ECDSAAdd.Arithmetic.balancedSharedCanonicalTapeReplay_quotient
#print axioms ECDSAAdd.Arithmetic.balancedSharedCanonicalTapeReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedSharedBoundary_clean
#print axioms ECDSAAdd.Arithmetic.balancedSharedTranscriptReplayLayout
#print axioms ECDSAAdd.Arithmetic.balancedSharedReplayProgram_eq
#print axioms ECDSAAdd.Arithmetic.balancedSharedReplayProgram_counts
#print axioms ECDSAAdd.Arithmetic.balancedSharedDivision_double_frame
#print axioms ECDSAAdd.Arithmetic.balancedSharedDivision_replay_frame
#print axioms ECDSAAdd.Arithmetic.balancedSharedFieldDivision_spec
#print axioms ECDSAAdd.Arithmetic.balancedSharedFieldDivision_counts
#print axioms ECDSAAdd.Arithmetic.balancedSharedFieldDivision
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptDouble_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptBody_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptCell_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptReplay_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptCanonicalReplay_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptCanonicalReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedCanonicalReplay_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedCanonicalTapeReplay_product
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedCanonicalTapeReplay_counts
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedReplayProgram_eq
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedReplayProgram_counts
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedMultiplication_replay_frame
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedFieldMultiplication_spec
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedFieldMultiplication_counts
#print axioms ECDSAAdd.Arithmetic.balancedInverseSharedFieldMultiplication
#print axioms ECDSAAdd.Arithmetic.BalancedConvert.support
#print axioms ECDSAAdd.Arithmetic.balancedTranscriptReplay_support
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.support
#print axioms ECDSAAdd.Arithmetic.BalancedInverse.qubitBound
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptReplay_support
#print axioms ECDSAAdd.Arithmetic.balancedInverseTranscriptCanonicalReplay_support
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.unary
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.copy
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.kernelSites
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.converters
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.replay
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.replayPrograms
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.endpoints
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.declaredEndpoints
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeed_counts
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeed_frame
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeed_spec
#print axioms ECDSAAdd.Arithmetic.literalSkywalkUnseed_spec
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeed_encode
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeed_roundtrip
#print axioms ECDSAAdd.Arithmetic.literalSkywalkUnseed_preserves_outsideA
#print axioms ECDSAAdd.Arithmetic.literalSkywalkPoolSeed_valid
#print axioms ECDSAAdd.Arithmetic.literalSkywalkPoolSeed_boundary
#print axioms ECDSAAdd.Arithmetic.literalSkywalkPoolSeed_qubitBound
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeedSharedBridge_oldSeed_outsideA
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeedSharedBridge_oldUnseed_outsideA
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeedSharedBridge_seed_eq
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeedSharedBridge_unseed_eq
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeedSharedBridge_seed_spec
#print axioms ECDSAAdd.Arithmetic.literalSkywalkSeedSharedBridge_unseed_spec
#print axioms ECDSAAdd.Arithmetic.directSkywalkLiteralSeed_seed_eq
#print axioms ECDSAAdd.Arithmetic.directSkywalkLiteralSeed_unseed_eq
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_jointND
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_workAway
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_work_subset
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_clean_frame
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_double_frame
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_half_frame
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_support
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_no_old_bank
#print axioms ECDSAAdd.Arithmetic.borrowedSkywalkUnary_resources
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.kernelSites
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.converters
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.replay
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.tapeSupport
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.replayPrograms
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.copy
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.copyLow
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.unary
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.integerSegments
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.endpoints
#print axioms ECDSAAdd.Arithmetic.BorrowedSkywalkCompactSupport.kernel
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.compactPointSites_nodup
#print axioms ECDSAAdd.Arithmetic.ControlledPointLayout.compactSharedMap_support
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_compact_support
#print axioms ECDSAAdd.Arithmetic.pointDirectSkywalkArithmetic_compact_resources
#print axioms ECDSAAdd.Arithmetic.pointDialogGeneric_compact_wires
#print axioms ECDSAAdd.Arithmetic.pointDialogFinite_compact_wires
#print axioms ECDSAAdd.Arithmetic.BalancedSharedFieldSupport.compactSubsetShared
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedField.program_correct
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedInverse.program_correct
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedCanonical.canonicalTapeReplay_quotient
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedCanonical.canonicalTapeReplay_counts
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedInverseCanonical.canonicalTapeReplay_product
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedInverseCanonical.canonicalTapeReplay_counts
#print axioms ECDSAAdd.Arithmetic.offsetBorrowedSharedFieldDivision_spec
#print axioms ECDSAAdd.Arithmetic.offsetBorrowedSharedFieldDivision_counts
#print axioms ECDSAAdd.Arithmetic.offsetBorrowedInverseSharedFieldMultiplication_spec
#print axioms ECDSAAdd.Arithmetic.offsetBorrowedInverseSharedFieldMultiplication_counts
#print axioms ECDSAAdd.Arithmetic.offsetBorrowedDirectArithmetic_run
#print axioms ECDSAAdd.Arithmetic.offsetBorrowedDirectArithmetic_counts
#print axioms ECDSAAdd.Arithmetic.pointOffsetBorrowedArithmetic_correct
#print axioms ECDSAAdd.Arithmetic.pointOffsetBorrowedArithmetic_counts
#print axioms ECDSAAdd.Arithmetic.OffsetBorrowedSupport.kernel
#print axioms ECDSAAdd.Arithmetic.pointOffsetBorrowedArithmetic_compact_support
#print axioms ECDSAAdd.Arithmetic.pointOffsetBorrowedArithmetic_compact_resources
LEAN
)
task_axiom_lean_rc=$?
set -e
printf '%s\n' "$axioms"
printf '%s\n' "$axioms" > "${ECDSA_EXACT_AXIOM_LOG:-/tmp/ecdsadd-point-axioms.log}"
if [[ "$task_axiom_lean_rc" -ne 0 ]]; then exit "$task_axiom_lean_rc"; fi
python3 - "${ECDSA_EXACT_AXIOM_LOG:-/tmp/ecdsadd-point-axioms.log}" "$0" <<'PY'
import re,sys
from pathlib import Path
text=Path(sys.argv[1]).read_text();script=Path(sys.argv[2]).read_text()
wanted=re.findall(r'^#print axioms (.+)$',script,re.M)
actual=re.findall(r"^'([^']+)'",text,re.M)
assert actual==wanted,('Missing or reordered public axiom outputs',len(actual),len(wanted))
entries=re.findall(r"^'([^']+)' (?:does not depend on any axioms|depends on axioms:\s*\[([^\]]*)\])",text,re.M)
assert [name for name,_ in entries]==wanted,('Unparsed axiom outputs',len(entries),len(wanted))
allowed={'propext','Classical.choice','Quot.sound'}
for name,body in entries:
 names=set(filter(None,re.split(r'[\s,]+',body)))
 assert names<=allowed,(name,names)
print('All',len(actual),'public entry-point axiom audits passed the exact whitelist.')
PY
